CREATE PROCEDURE "informix".sp_provision_de_intereses(P_EMPRESA    VARCHAR(3)
       ,P_EJECUTIVO  VARCHAR(8)
       ,P_COMMIT     INTEGER
       ) RETURNING VARCHAR(5), VARCHAR(80);

DEFINE P_COD_RET VARCHAR(5);
DEFINE P_MENSAJE VARCHAR(80);

DEFINE V_FECHA_CTL   DATE;
DEFINE V_FECHA_CTL2  DATE;
DEFINE V_FECHA_HOY   DATE;
DEFINE V_PROX_FECHA  DATE;
DEFINE V_FIN_MES     DATE;
DEFINE V_FECHA_CUOTA DATE;
DEFINE V_FECHA_CUOTA_INI DATE;
DEFINE V_FECHA_CUOTA_UNO DATE;
DEFINE V_FECHA_CUOTA_S1 DATE;
DEFINE V_FECHA_CORTE DATE;

DEFINE V_NUM_CREDITO   LIKE BDICRED:SD_MAECRED.NUM_CREDITO;
DEFINE V_NUM_PRODUCTO  LIKE BDICRED:SD_MAECRED.NUM_PRODUCTO;
DEFINE V_DIVISA        LIKE BDICRED:SD_MAECRED.DIVISA;
DEFINE V_SUCURSAL      LIKE BDICRED:SD_MAECRED.SUCURSAL;
DEFINE V_TASA_INTERES  LIKE BDICRED:SD_MAECRED.TASA_INTERES;
DEFINE V_FECHA_FIN_PR  DATE;
DEFINE V_SDO_CAPITAL   DECIMAL(18,2);
DEFINE V_MONTO_CUOTA   DECIMAL(18,2);
DEFINE V_MONTO_FINANCIADO DECIMAL(18,2);
DEFINE V_TIPO_CALCULO  VARCHAR(3);
DEFINE V_DIAS_CUOTA    INTEGER;
DEFINE V_MANEJA_LINEA  LIKE BDICRED:SD_DEFINICION.MANEJA_LINEA;

DEFINE V_NVO_INT_DIARIO  DECIMAL(18,2);
DEFINE V_NVO_SDO_CAPITAL DECIMAL(18,2);

DEFINE V_COMMIT      INTEGER;
DEFINE V_DIAS_ANIO   INTEGER;
DEFINE V_DIAS_CALC   INTEGER;
DEFINE V_DIAS_PROV   INTEGER;
DEFINE V_INT_DIARIO  DECIMAL(18,2);
DEFINE V_TIPO_FECHA  VARCHAR(1);

DEFINE V_FECHA_C  INTEGER;
DEFINE V_FECHA_M  INTEGER;
DEFINE V_FECHA_P  INTEGER;

DEFINE V_INICIO_PERIODO VARCHAR(1);
DEFINE V_ACUM_PROV_NOR  VARCHAR(1);
DEFINE V_CAMBIO_MES     VARCHAR(1);

DEFINE V_TRABAJO0  VARCHAR(1);
DEFINE V_TRABAJO   VARCHAR(1);

DEFINE V_FUNCION VARCHAR(3);

DEFINE  SQL_ERR    INTEGER;
DEFINE  ISAM_ERR   INTEGER;
DEFINE  ERROR_INFO VARCHAR(80);

BEGIN
  ON EXCEPTION SET SQL_ERR, ISAM_ERR, ERROR_INFO
    LET P_COD_RET = SQL_ERR;
    LET P_MENSAJE = ERROR_INFO;
    UPDATE SD_CONTPROC
    SET    STATUS_PROC = 'C',
           HORA_FIN    = CURRENT,
           COD_RET     = P_COD_RET,
           MENSAJE     = P_MENSAJE
    WHERE  EMPRESA     = P_EMPRESA
    AND    PROCESO     = 'provision'
    AND    FECHA       = V_FECHA_HOY;

    RETURN P_COD_RET, P_MENSAJE;
  END EXCEPTION;



  LET P_COD_RET = '00000';
  LET P_MENSAJE = 'PROCESO EXITOSO';
  LET V_FECHA_CUOTA = NULL;
  LET V_COMMIT  = 0;
  LET V_FECHA_C = 0;
  LET V_FECHA_M = 0;
  LET V_FECHA_P = 0;
  LET V_FUNCION = '606'; /* Cierre. Provisión de Intereses Ordinarios */

  SELECT F.FECHA_HOY, F.PROX_FECHA, F.ULT_DIA_MES
  INTO V_FECHA_HOY, V_PROX_FECHA, V_FIN_MES
  FROM   SD_FECHAS F
  WHERE EMPRESA = P_EMPRESA;

  SELECT NVL(MAX(STATUS_PROC), 'N')
  INTO   V_TRABAJO0
  FROM   SD_CONTPROC
  WHERE  EMPRESA     = P_EMPRESA
  AND    PROCESO     = 'trasp cart venc'
  AND    FECHA       = V_FECHA_HOY;

  IF V_TRABAJO0 = 'F' THEN
  SELECT NVL(MAX(STATUS_PROC), 'N')
  INTO   V_TRABAJO
  FROM   SD_CONTPROC
  WHERE  EMPRESA     = P_EMPRESA
  AND    PROCESO     = 'provision'
  AND    FECHA       = V_FECHA_HOY;

  IF V_TRABAJO = 'N' THEN

    INSERT INTO SD_CONTPROC (EMPRESA, PROCESO, FECHA, STATUS_PROC, EJECUTIVO,
                             HORA_INICIO, HORA_FIN, COD_RET, MENSAJE)
    VALUES (P_EMPRESA, 'provision', V_FECHA_HOY, 'I', P_EJECUTIVO, CURRENT, NULL,
                NULL, NULL);

    SELECT VALOR INTO V_DIAS_ANIO FROM SD_PARAM WHERE COD_PARAM = '24';

    CREATE TEMP TABLE FECHAS_CTL (FECHA DATE, VALOR VARCHAR(1));

    FOREACH SELECT M.NUM_CREDITO, M.NUM_PRODUCTO, M.DIVISA, M.SUCURSAL
               , NVL(M.TASA_INTERES,0), FECHA_FIN_PRORRATEO, NVL(D.SDO_CAPITAL,0)
               , M.TIPO_CALCULO
          INTO V_NUM_CREDITO, V_NUM_PRODUCTO, V_DIVISA, V_SUCURSAL
             , V_TASA_INTERES, V_FECHA_FIN_PR, V_SDO_CAPITAL
             , V_TIPO_CALCULO
          FROM SD_MAECRED M, SD_MAESDOS D
          WHERE D.NUM_CREDITO = M.NUM_CREDITO
          AND D.EMPRESA = M.EMPRESA
          AND M.BANDERA_MINISTRA = 'M'
          AND SUBSTR(M.STATUS_CRED, 1, 1) NOT IN ('C', 'F', 'O')
--          AND M.NUM_CREDITO = '210010541401000'
          AND M.EMPRESA = P_EMPRESA

      --VERIFICA SI EL PRODUCTO MANEJA LINEA
      SELECT NVL(MANEJA_LINEA,'N')
      INTO V_MANEJA_LINEA
      FROM SD_DEFINICION
      WHERE NUM_PRODUCTO = V_NUM_PRODUCTO
      AND EMPRESA = P_EMPRESA;

      IF V_MANEJA_LINEA = 'N' THEN

        SELECT MIN(P.FECHA_CUOTA)
        INTO V_FECHA_CUOTA
        FROM SD_MAECRED M, SD_PAGINTER P
        WHERE 1 = 1
        AND (((P.FECHA_CUOTA + NVL(M.DIAS_TRASP_INT,0))< V_PROX_FECHA
             AND P.STATUS_CUOTA = '7'
             AND (P.FECHA_CUOTA BETWEEN (V_FECHA_HOY+1) AND (V_PROX_FECHA-1)))
           OR
             (P.FECHA_CUOTA BETWEEN (V_FECHA_HOY+1) AND (V_PROX_FECHA-1)
              AND P.STATUS_CUOTA = '1'
              AND SUBSTR(M.STATUS_CRED, 1, 1) IN ('A', 'B', 'T')))
        AND P.NUM_CREDITO = M.NUM_CREDITO
        AND P.EMPRESA = M.EMPRESA
        AND M.NUM_CREDITO = V_NUM_CREDITO
        AND M.EMPRESA = P_EMPRESA;

        DELETE FROM FECHAS_CTL;
        INSERT INTO FECHAS_CTL VALUES(V_FECHA_CUOTA, 'C');
        INSERT INTO FECHAS_CTL VALUES(V_PROX_FECHA, 'P');
        INSERT INTO FECHAS_CTL VALUES(V_FIN_MES, 'M');

        --OBTIENE EL MONTO DEL INTERES QUE SE DEBE DE PROVISIONAR
        IF V_TIPO_CALCULO = '01' THEN
          LET V_INT_DIARIO = V_SDO_CAPITAL * ((V_TASA_INTERES/100)/V_DIAS_ANIO);
        ELIF V_TIPO_CALCULO = '02' THEN
          --OBTIENE LA FECHA CON STATUS 1
          SELECT MIN(FECHA_CUOTA)
          INTO V_FECHA_CUOTA_S1
          FROM SD_PAGINTER P1
          WHERE P1.STATUS_CUOTA = '1'
          AND P1.NUM_CREDITO = V_NUM_CREDITO
          AND P1.EMPRESA = P_EMPRESA;

          --OBTIENE PRIMER CUOTRA DE INTERES
          SELECT MIN(FECHA_CUOTA)
          INTO V_FECHA_CUOTA_UNO
          FROM SD_PAGINTER
          WHERE NUM_CREDITO = V_NUM_CREDITO
          AND EMPRESA = P_EMPRESA;

          --OBTIENE FECHA DE INICIO DE PERIODO
          IF V_FECHA_CUOTA_UNO = V_FECHA_CUOTA_S1 THEN
            SELECT MAX(FECHA_OTORGA) + 1
            INTO V_FECHA_CUOTA_INI
            FROM SD_DETMINIS
            WHERE NUM_CREDITO = V_NUM_CREDITO
            AND EMPRESA = P_EMPRESA;
          ELSE
            SELECT MAX(FECHA_CUOTA) + 1
            INTO V_FECHA_CUOTA_INI
            FROM SD_PAGINTER
            WHERE FECHA_CUOTA < V_FECHA_CUOTA
            AND NUM_CREDITO = V_NUM_CREDITO
            AND EMPRESA = P_EMPRESA;
          END IF;
        END IF;
        LET V_FECHA_CTL = V_FECHA_HOY;

        FOREACH SELECT FECHA, VALOR INTO V_FECHA_CTL2, V_TIPO_FECHA FROM FECHAS_CTL ORDER BY FECHA

          --EXISTE VENCIMIENTO DE CUOTA DE INTERES
          IF V_TIPO_FECHA = 'C' AND V_FECHA_CUOTA IS NOT NULL THEN
            IF V_TIPO_CALCULO = '01' THEN
              LET V_DIAS_CALC = V_FECHA_CUOTA - V_FECHA_CTL;
              LET V_DIAS_PROV = V_DIAS_CALC;
            ELIF V_TIPO_CALCULO = '02' THEN
              SELECT (NVL(P.MONTO_CUOTA,0) - NVL(MONTO_FINANCIADO,0))
              INTO V_INT_DIARIO
              FROM SD_PAGINTER P
              WHERE P.FECHA_CUOTA = V_FECHA_CUOTA_S1
              AND P.NUM_CREDITO = V_NUM_CREDITO
              AND P.EMPRESA = P_EMPRESA;
              LET V_DIAS_CALC = 1;
              LET V_DIAS_PROV = V_DIAS_CALC;
              LET V_SDO_CAPITAL = 0;
            END IF;
            LET V_INICIO_PERIODO = 'N';
            LET V_ACUM_PROV_NOR  = 'N';
            LET V_CAMBIO_MES     = 'N';

            --SE PRVISIONA
            EXECUTE PROCEDURE SP_PROVISION
               (P_EMPRESA, V_NUM_CREDITO, P_EJECUTIVO, V_NUM_PRODUCTO,
                V_SUCURSAL, V_DIVISA, V_DIAS_CALC, V_FECHA_HOY,
                V_FUNCION, V_INT_DIARIO, V_SDO_CAPITAL,
                V_CAMBIO_MES, V_ACUM_PROV_NOR, V_INICIO_PERIODO,
                V_TIPO_CALCULO, V_DIAS_PROV
               )INTO P_COD_RET, P_MENSAJE;

            --*****SE TRASPASA A CARTERA VENCIDA
            --EXECUTE PROCEDURE SP_TRASP_CART_VENC_X_CRED
            --     (P_EMPRESA, V_NUM_CREDITO, V_FECHA_CUOTA, P_EJECUTIVO
            --     )INTO P_COD_RET, P_MENSAJE;

            LET V_FECHA_CTL = V_FECHA_CUOTA;
            LET V_FECHA_C = 1;

          --*****EXISTE FIN DE MES
          ELIF V_TIPO_FECHA = 'M' THEN
            IF V_TIPO_CALCULO = '01' THEN
              LET V_DIAS_CALC = V_FIN_MES - V_FECHA_CTL;
              LET V_DIAS_CALC = V_DIAS_CALC + 1;
              LET V_DIAS_PROV = V_DIAS_CALC;

            ELIF V_TIPO_CALCULO = '02' THEN
              LET V_DIAS_CUOTA = V_FECHA_CUOTA_S1 - V_FECHA_CUOTA_INI;
              LET V_DIAS_CALC = V_FIN_MES - V_FECHA_CTL;
              LET V_DIAS_CALC = V_DIAS_CALC + 1;
              LET V_DIAS_PROV = V_DIAS_CALC;

              --CALCULA EL IMPORTE DE LA CUOTA DIARIO
              SELECT NVL(P.MONTO_CUOTA,0), NVL(P.MONTO_FINANCIADO,0)
              INTO V_MONTO_CUOTA, V_MONTO_FINANCIADO
              FROM SD_PAGINTER P
              WHERE P.FECHA_CUOTA = V_FECHA_CUOTA_S1
              AND P.NUM_CREDITO = V_NUM_CREDITO
              AND P.EMPRESA = P_EMPRESA;

              LET V_INT_DIARIO = ((V_MONTO_CUOTA/V_DIAS_CUOTA) * V_DIAS_CALC);

              --OBTIENE LA CUOTA DE INTERES DIARIA * LOS DIAS A PROVISIONAR
              LET V_SDO_CAPITAL = V_INT_DIARIO - V_MONTO_FINANCIADO;

              IF V_SDO_CAPITAL < 0 THEN
                LET V_DIAS_CALC = 0;
                LET V_INT_DIARIO = 0;
              ELSE
                LET V_DIAS_CALC = 1;
                LET V_INT_DIARIO = V_SDO_CAPITAL;
                LET V_SDO_CAPITAL = 0;
              END IF;
            END IF;

            IF V_DIAS_CALC > 0 THEN
              LET V_INICIO_PERIODO = 'N';
              LET V_ACUM_PROV_NOR  = 'N';
              LET V_CAMBIO_MES     = 'N';
              EXECUTE PROCEDURE SP_PROVISION
                 (P_EMPRESA, V_NUM_CREDITO, P_EJECUTIVO,V_NUM_PRODUCTO,
                  V_SUCURSAL, V_DIVISA, V_DIAS_CALC, V_FECHA_HOY,
                  V_FUNCION, V_INT_DIARIO, V_SDO_CAPITAL,
                  V_CAMBIO_MES, V_ACUM_PROV_NOR, V_INICIO_PERIODO,
                  V_TIPO_CALCULO, V_DIAS_PROV
                 )INTO P_COD_RET, P_MENSAJE;
            ELSE
              EXECUTE PROCEDURE SP_INICIALIZA_ACUM_PROV_NORMAL
                 (P_EMPRESA, V_NUM_CREDITO
                 ) INTO P_COD_RET, P_MENSAJE;
            END IF;

            EXECUTE PROCEDURE SP_TRASPASO_HIST_MAESDOS
               (P_EMPRESA, V_NUM_CREDITO, V_FECHA_HOY
               ) INTO P_COD_RET, P_MENSAJE;

            LET V_FECHA_CTL = V_FIN_MES;
            LET V_FECHA_M = 1;

          --*****EN PROXIMA FECHA
          ELIF V_TIPO_FECHA = 'P' THEN
            IF V_TIPO_CALCULO = '01' THEN
              LET V_DIAS_CALC = V_PROX_FECHA - V_FECHA_CTL;
              LET V_DIAS_PROV = V_DIAS_CALC;
            ELIF V_TIPO_CALCULO = '02' THEN
              LET V_DIAS_CALC = 0;
              LET V_DIAS_PROV = V_DIAS_CALC;
            END IF;
            LET V_INICIO_PERIODO = 'N';
            LET V_ACUM_PROV_NOR  = 'N';
            LET V_CAMBIO_MES     = 'N';

            --SE DIO CAMBIO DE MES
            IF V_FECHA_M = 1 AND V_TIPO_CALCULO = '01' THEN
              IF V_DIAS_CALC > 0 THEN
                LET V_INICIO_PERIODO = 'N';
                LET V_ACUM_PROV_NOR  = 'S';
                LET V_CAMBIO_MES     = 'S';
                EXECUTE PROCEDURE SP_PROVISION
                    (P_EMPRESA, V_NUM_CREDITO, P_EJECUTIVO,V_NUM_PRODUCTO,
                     V_SUCURSAL, V_DIVISA, V_DIAS_CALC, V_FECHA_HOY,
                     V_FUNCION, V_INT_DIARIO, V_SDO_CAPITAL,
                     V_CAMBIO_MES, V_ACUM_PROV_NOR, V_INICIO_PERIODO,
                     V_TIPO_CALCULO, V_DIAS_PROV
                    )INTO P_COD_RET, P_MENSAJE;
              ELSE
                EXECUTE PROCEDURE SP_ACTUALIZA_ACUM_CAMBIO_MES
                   (P_EMPRESA, V_NUM_CREDITO
                   ) INTO P_COD_RET, P_MENSAJE;
              END IF;
            END IF;

            --SE DIO VENCIMIENTO DE CUOTA DE INTERES, RECALCULA LOS SALDOS
            IF V_FECHA_C = 1 AND V_TIPO_CALCULO = '01' THEN
              SELECT MAX((S.SDO_CAPITAL * (M.TASA_INTERES/100))/(P.VALOR)),
                     MAX(S.SDO_CAPITAL)
              INTO   V_INT_DIARIO, V_SDO_CAPITAL
              FROM   SD_MAECRED M, SD_MAESDOS S, SD_PARAM P
              WHERE  M.EMPRESA     = S.EMPRESA
              AND    M.NUM_CREDITO = S.NUM_CREDITO
              AND    P.EMPRESA     = M.EMPRESA
              AND    P.COD_PARAM   = '24'
              AND    M.NUM_CREDITO = V_NUM_CREDITO
              AND    M.EMPRESA     = P_EMPRESA;

              LET V_INICIO_PERIODO = 'S';
              LET V_ACUM_PROV_NOR  = 'S';
              LET V_CAMBIO_MES     = 'N';

              IF V_DIAS_CALC > 0 THEN
                EXECUTE PROCEDURE SP_ACTUALIZA_ACUM_INI_PERIODO
                    (P_EMPRESA, V_NUM_CREDITO, V_FECHA_CUOTA
                    )INTO P_COD_RET, P_MENSAJE;
              END IF;
            END IF;

            IF V_DIAS_CALC > 0 THEN
               EXECUTE PROCEDURE SP_PROVISION
                    (P_EMPRESA, V_NUM_CREDITO, P_EJECUTIVO,V_NUM_PRODUCTO,
                     V_SUCURSAL, V_DIVISA, V_DIAS_CALC, V_FECHA_HOY,
                     V_FUNCION, V_INT_DIARIO, V_SDO_CAPITAL,
                     V_CAMBIO_MES, V_ACUM_PROV_NOR, V_INICIO_PERIODO,
                     V_TIPO_CALCULO, V_DIAS_PROV
                    )INTO P_COD_RET, P_MENSAJE;
            END IF;

            EXIT FOREACH;
          END IF; --TIPO DE FECHA
        END FOREACH; --FECHAS
      ELSE
        EXECUTE PROCEDURE BDICRED:ProvisionLineaCred(P_EMPRESA, V_NUM_CREDITO)
                INTO P_COD_RET;
        IF P_COD_RET = '000' THEN
          LET P_COD_RET = '00000';
          LET P_MENSAJE = 'PROCESO EXITOSO';
        END IF;

      END IF; --MANEJA LINEA
    END FOREACH; --CREDITOS

    DROP TABLE FECHAS_CTL;

  ELIF V_TRABAJO = 'F' THEN
    LET P_COD_RET = '950';
    LET P_MENSAJE = 'Ya se ejecuto el proceso';

  ELIF V_TRABAJO = 'I' THEN
    LET P_COD_RET = '951';
    LET P_MENSAJE = 'El proceso se esta ejecutando';

  ELIF V_TRABAJO = 'C' THEN
    LET P_COD_RET = '952';
    LET P_MENSAJE = 'El proceso se ejecuto con error';

  END IF;

  IF P_COD_RET = '00000' THEN
    UPDATE SD_CONTPROC
    SET    STATUS_PROC = 'F',
           HORA_FIN    = CURRENT,
           COD_RET     = P_COD_RET,
           MENSAJE     = P_MENSAJE
    WHERE  EMPRESA     = P_EMPRESA
    AND    PROCESO     = 'provision'
    AND    FECHA       = V_FECHA_HOY;

  ELSE
    UPDATE SD_CONTPROC
    SET    STATUS_PROC = 'C',
           HORA_FIN    = CURRENT,
           COD_RET     = P_COD_RET,
           MENSAJE     = P_MENSAJE
    WHERE  EMPRESA     = P_EMPRESA
    AND    PROCESO     = 'provision'
    AND    FECHA       = V_FECHA_HOY;
  END IF;
  ELSE
     /* Es necesario realizar el traspaso a cartera vencida antes de la provisión */
     LET P_COD_RET = '959';
     LET P_MENSAJE = 'Es necesario realizar el traspaso a cartera vencida antes';

     INSERT INTO SD_CONTPROC (EMPRESA, PROCESO, FECHA, STATUS_PROC, EJECUTIVO,
                              HORA_INICIO, HORA_FIN, COD_RET, MENSAJE)
     VALUES (P_EMPRESA, 'provision', V_FECHA_HOY, 'C', P_EJECUTIVO, CURRENT,
             TODAY, P_COD_RET, P_MENSAJE);

  END IF;
  RETURN P_COD_RET, P_MENSAJE;
END;
END PROCEDURE;