CREATE PROCEDURE "informix".genera_mov_dia( P_EMPRESA      VARCHAR(3)
                               , P_NUM_CREDITO  VARCHAR(20)
                               )
RETURNING VARCHAR(8), VARCHAR(80);

DEFINE  V_NUM_PRODUCTO  LIKE SD_MAECRED.NUM_PRODUCTO;
DEFINE  V_CODIGO_REF    LIKE SD_TRANSFUN.CODIGO_REF;
DEFINE  V_CODIGO_FUN    LIKE SD_TRANSFUN.CODIGO_FUN;
DEFINE  V_FECHA_HOY     DATE;
DEFINE  V_MONTO         INTEGER;
DEFINE  V_MONTO_MOV     INTEGER;
DEFINE  V_FOLIO_SUC     VARCHAR(16);
DEFINE  V_SUCURSAL      LIKE SD_MAECRED.SUCURSAL;
DEFINE  V_DIVISA        LIKE SD_MAECRED.DIVISA;
DEFINE  V_TRANSACC_SUC  VARCHAR(4);

DEFINE  P_COD_RET  VARCHAR(8);
DEFINE  P_MENSAJE  VARCHAR(80);

DEFINE V_COD_INS      LIKE SD_FUENTES_X_CRED.CODIGO_INS;
DEFINE V_PORCENT_PART INTEGER;
DEFINE V_COD_REF      LIKE SD_TRANSFUN.CODIGO_REF;
DEFINE V_CANTIDAD     INTEGER;

BEGIN
   LET V_TRANSACC_SUC = '0000';
   LET P_COD_RET = '00000';
   LET P_MENSAJE = 'PROCESO EXITOSO';

   --SELECCIONA LA FECHA DE HOY
   SELECT FECHA_HOY
   INTO   V_FECHA_HOY
   FROM   SD_FECHAS
   WHERE  EMPRESA = P_EMPRESA;

   --SELECCIONA EL NUMERO DE PRODUCTO, EL FOLIO_SUC, LA SUCURSAL, LA DIVISA
   SELECT NUM_PRODUCTO, SUBSTR(USER,1,8) || replace(replace(extend(current, hour to fraction(2)),':',''),'.','') FOLIO_SUC, SUCURSAL, DIVISA
   INTO   V_NUM_PRODUCTO, V_FOLIO_SUC, V_SUCURSAL, V_DIVISA
   FROM   SD_MAECRED
   WHERE  EMPRESA     = P_EMPRESA
   AND    NUM_CREDITO = P_NUM_CREDITO;

   --SELECCIONA EL MONTO TOTAL DEL CREDITO
   SELECT MONTO_OTORGADO
   INTO   V_MONTO
   FROM   SD_MAESDOS
   WHERE  EMPRESA     = P_EMPRESA
   AND    NUM_CREDITO = P_NUM_CREDITO;

   --EJECUTA LA GENERACION DEL MOVIMIENTO
   FOREACH FTES FOR  SELECT FTE.CODIGO_INS, 100 PORCENT_PART, MIN(TRA.CODIGO_REF) CODIGO_REF, COUNT(TRA.CODIGO_REF) CANTIDAD
                     INTO   V_COD_INS, V_PORCENT_PART, V_COD_REF, V_CANTIDAD
                     FROM   SD_FUENTES_X_CRED AS FTE
                           ,SD_TRANSFUN       AS TRA
                     WHERE  TRA.CODIGO_INS   = FTE.CODIGO_INS
                     AND    TRA.EMPRESA      = FTE.EMPRESA
                     AND    TRA.CODIGO_FUN   = '001'
                     AND    FTE.INDIC_PROPIO = 1
                     AND    FTE.EMPRESA      = P_EMPRESA
                     AND    FTE.NUM_CREDITO  = P_NUM_CREDITO
                     GROUP BY FTE.CODIGO_INS, PORCENT_PART

      IF V_CANTIDAD > 1 THEN
         LET P_COD_RET = '00001';
         LET P_MENSAJE = 'ESTE CREDITO NO TIENE UN CÓDIGO DE FUNCIÓN BIEN DEFINIDO';
         RETURN P_COD_RET, P_MENSAJE;
      ELSE
         LET V_MONTO_MOV = V_MONTO * (V_PORCENT_PART / 100);
         EXECUTE PROCEDURE  GENMOV( P_EMPRESA	    , P_NUM_CREDITO
                                  , V_NUM_PRODUCTO  , V_COD_REF
                                  , '001'           , V_FECHA_HOY
                                  , V_MONTO_MOV     , V_FOLIO_SUC
                                  , V_SUCURSAL      , V_DIVISA
                                  , V_TRANSACC_SUC )
                             INTO   P_COD_RET, P_MENSAJE;
      END IF;
   END FOREACH;

   RETURN P_COD_RET, P_MENSAJE;

END;
END PROCEDURE;