CREATE PROCEDURE "informix".sp_provision_moratorios(P_EMPRESA        VARCHAR(3),
       P_EJECUTIVO      VARCHAR(8),
       P_FECHA_HOY      DATE,
       P_NUM_COMMITS    INTEGER
      ) RETURNING VARCHAR(6), VARCHAR(80);

DEFINE P_COD_RET  VARCHAR(6);
DEFINE P_MENSAJE  VARCHAR(80);

DEFINE V_FUNCION       VARCHAR(3);
DEFINE V_TRABAJO0	     VARCHAR(1);
DEFINE V_TRABAJO       VARCHAR(1);
DEFINE V_HORA_INICIO   DATETIME HOUR TO MINUTE;
DEFINE V_DIAS_ANUALES  INTEGER;
DEFINE V_PROX_FECHA    DATE;
DEFINE V_FIN_MES       DATE;
DEFINE V_DIAS_CALC1    INTEGER;
DEFINE V_DIAS_CALC2    INTEGER;

DEFINE V_NUM_CREDITO     VARCHAR(20);
DEFINE V_FECHA_CUOTA     DATE;
DEFINE V_NUM_PRODUCTO    LIKE SD_MAECRED.NUM_PRODUCTO;
DEFINE V_SUCURSAL        LIKE SD_MAECRED.SUCURSAL;
DEFINE V_DIVISA          LIKE SD_MAECRED.DIVISA;
DEFINE V_COD_TASA_MORA   DECIMAL(18,2);
DEFINE V_TASA_MORA_ADIC  VARCHAR(1);
DEFINE V_NUM_REG         INTEGER;

DEFINE V_TASA_BASE         LIKE BDICRED:SD_MAECRED.TASA_INTERES;
DEFINE V_TASA_MORA         LIKE BDICRED:SD_MAECRED.TASA_MORATORIOS;
DEFINE V_SOBRETASA         LIKE BDICRED:SD_MAECRED.SOBRETASA;
DEFINE V_SOBRETASA_MORA    LIKE BDICRED:SD_MAECRED.SOBRETASA_MORA;
DEFINE V_FACTOR_SOBRETASA  LIKE BDICRED:SD_MAECRED.FACTOR_SOBRETASA;
DEFINE V_FACT_SOBRET_MORA  LIKE BDICRED:SD_MAECRED.FACT_SOBRET_MORA;
DEFINE V_INT1              DECIMAL(18,2);
DEFINE V_INT2              DECIMAL(18,2);
DEFINE V_MORA_ORDI         DECIMAL(18,2);
DEFINE V_MORA_COPE         DECIMAL(18,2);
DEFINE V_SDO_CUOTA         DECIMAL(18,2);
DEFINE V_FECHA_PROX        DATE;

DEFINE V_INT_CUOTA         DECIMAL(18,2);

DEFINE  SQL_ERR      INTEGER;
DEFINE  ISAM_ERR     INTEGER;
DEFINE  ERROR_INFO   VARCHAR(80);
DEFINE V_CURRENT     DATETIME HOUR TO FRACTION;

BEGIN
  ON EXCEPTION SET SQL_ERR, ISAM_ERR, ERROR_INFO
     LET P_COD_RET  = SQL_ERR;
     LET P_MENSAJE  = ERROR_INFO;
     UPDATE SD_CONTPROC
     SET    STATUS_PROC = 'C',
            HORA_FIN    = V_CURRENT,
            COD_RET     = P_COD_RET,
            MENSAJE     = P_MENSAJE
     WHERE  EMPRESA     = P_EMPRESA
     AND    PROCESO     = 'provision mora'
     AND    FECHA       = P_FECHA_HOY;
     RETURN P_COD_RET, P_MENSAJE;
  END EXCEPTION;

  LET V_FUNCION = '607';
  LET P_COD_RET = '00000';
  LET P_MENSAJE = 'PROCESO EXITOSO';
  LET V_HORA_INICIO = CURRENT;
  LET V_DIAS_ANUALES = NULL;
  LET V_MORA_ORDI = 0;
  LET V_MORA_COPE = 0;

  SELECT CURRENT + 4 UNITS MINUTE, CURRENT + 3 UNITS MINUTE
    INTO V_CURRENT, V_HORA_INICIO 
    FROM DUAL;

  SELECT NVL(MAX(STATUS_PROC), 'N')
  INTO   V_TRABAJO0
  FROM   SD_CONTPROC
  WHERE  EMPRESA     = P_EMPRESA
  AND    PROCESO     = 'provision'
  AND    FECHA       = P_FECHA_HOY;

  IF V_TRABAJO0 = 'F' THEN

    SELECT NVL(MAX(STATUS_PROC), 'N')
    INTO   V_TRABAJO
    FROM   SD_CONTPROC
    WHERE  EMPRESA  = P_EMPRESA
    AND    PROCESO  = 'provision mora'
    AND    FECHA    = P_FECHA_HOY;

    IF V_TRABAJO = 'N' THEN

      INSERT INTO SD_CONTPROC (EMPRESA, PROCESO, FECHA, STATUS_PROC, EJECUTIVO,
                               HORA_INICIO, HORA_FIN, COD_RET, MENSAJE)
      VALUES (P_EMPRESA, 'provision mora', P_FECHA_HOY, 'I', P_EJECUTIVO,
              V_CURRENT, NULL, NULL, NULL);

      SELECT MAX((VALOR))
      INTO   V_DIAS_ANUALES
      FROM   SD_PARAM
      WHERE  COD_PARAM = '24';

      IF V_DIAS_ANUALES IS NOT NULL THEN

        FOREACH SELECT M.NUM_CREDITO, P.FECHA_CUOTA, M.NUM_PRODUCTO, M.DIVISA
                      ,M.SUCURSAL, NVL(D.SOBRETASA_MORA,0), D.TASA_MORA_ADIC
                      ,NVL(P.SALDO_CUOTA,0) SDO_CUOTA
                      ,NVL(M.TASA_INTERES,0), NVL(M.TASA_MORATORIOS,0)
                INTO V_NUM_CREDITO,V_FECHA_CUOTA,V_NUM_PRODUCTO,V_DIVISA
                    ,V_SUCURSAL, V_SOBRETASA_MORA, V_TASA_MORA_ADIC
                    ,V_SDO_CUOTA, V_TASA_BASE, V_TASA_MORA
                FROM SD_MAECRED M, SD_PAGOCAPIT P, SD_DEFINICION D
                WHERE P.FECHA_CUOTA+NVL(D.GRACIA_CALC_MORA,0) <= P_FECHA_HOY
                AND D.NUM_PRODUCTO  = M.NUM_PRODUCTO
                AND D.EMPRESA = M.EMPRESA
                AND P.STATUS_CUOTA IN ('2','7')
                AND P.NUM_CREDITO = M.NUM_CREDITO
                AND P.EMPRESA = M.EMPRESA
                AND SUBSTR(M.STATUS_CRED, 1, 1) NOT IN ('C', 'F', 'O')
                AND M.EMPRESA = P_EMPRESA
                AND NOT EXISTS (SELECT '1'
                                FROM SD_DETMORA DM
                                WHERE DM.FECHA_CUOTA = P.FECHA_CUOTA
                                AND   DM.NUM_CREDITO = P.NUM_CREDITO
                                AND   DM.EMPRESA = P.EMPRESA)

            SELECT NVL(MONTO_CUOTA,0) 
            INTO V_INT_CUOTA
            FROM SD_PAGINTER
            WHERE FECHA_CUOTA = V_FECHA_CUOTA
            AND NUM_CREDITO = V_NUM_CREDITO
            AND EMPRESA = P_EMPRESA;

            LET V_INT2 = (V_SDO_CUOTA + V_INT_CUOTA) * (V_TASA_MORA/100);

            --SE EJECUTA LA PROVISION DEMORATORIOS
            EXECUTE PROCEDURE BDICRED:SP_PROVISION_MORAT
                  (P_EMPRESA, V_NUM_CREDITO, V_FECHA_CUOTA,
                   P_EJECUTIVO, V_NUM_PRODUCTO, V_SUCURSAL,
                   V_DIVISA, P_FECHA_HOY, V_FUNCION,
                   V_INT2,0,1
                  )INTO P_COD_RET, P_MENSAJE;

        END FOREACH;
      END IF;
    ELIF V_TRABAJO = 'F' THEN
      LET P_COD_RET = '953';
      LET P_MENSAJE = 'El proceso concluyo con exito';
    ELIF V_TRABAJO = 'I' THEN
      LET P_COD_RET = '954';
      LET P_MENSAJE = 'El proceso esta en ejecucion';
    ELIF V_TRABAJO = 'C' THEN
      LET P_COD_RET = '955';
      LET P_MENSAJE = 'El proceso ya se ejecuto y termino con error';
    END IF;

    IF P_COD_RET = '00000' THEN

       UPDATE SD_CONTPROC
       SET    STATUS_PROC = 'F',
              HORA_FIN    = V_CURRENT,
              COD_RET     = P_COD_RET,
              MENSAJE     = P_MENSAJE
       WHERE  EMPRESA     = P_EMPRESA
       AND    PROCESO     = 'provision mora'
       AND    FECHA       = P_FECHA_HOY;

     ELSE
       IF P_COD_RET NOT IN ('953', '954', '955') THEN
          UPDATE SD_CONTPROC
          SET    STATUS_PROC = 'C',
                 HORA_FIN    = V_CURRENT,
                 COD_RET     = P_COD_RET,
                 MENSAJE     = P_MENSAJE
          WHERE  EMPRESA     = P_EMPRESA
          AND    PROCESO     = 'provision mora'
          AND    FECHA       = P_FECHA_HOY;
       END IF;
     END IF;
  ELSE
    LET P_COD_RET = '960';
    LET P_MENSAJE = 'Debe ejecutar el proceso de Provision de Int. antes de Prov. de Morat.';

    INSERT INTO SD_CONTPROC (EMPRESA, PROCESO, FECHA, STATUS_PROC, EJECUTIVO,
                             HORA_INICIO, HORA_FIN, COD_RET, MENSAJE)
    VALUES (P_EMPRESA, 'provision mora', P_FECHA_HOY, 'C', P_EJECUTIVO, V_HORA_INICIO,
            V_CURRENT, P_COD_RET, P_MENSAJE);
  END IF;
  RETURN P_COD_RET, P_MENSAJE;
END;
END PROCEDURE;