-- ================================================================
-- DDL : SISTEMA-CREDITO-LATAM
-- DB2 z/OS  ·  esquema CREDPROD
-- ================================================================

CREATE TABLE CREDPROD.CLIENTES (
    CLI_ID            DECIMAL(10,0) NOT NULL,
    CLI_NOMBRE        CHAR(40)      NOT NULL,
    CLI_RFC           CHAR(13)      NOT NULL,
    CLI_SALDO_PROM    DECIMAL(15,2) DEFAULT 0,
    CLI_CREDITOS_ACT  SMALLINT      DEFAULT 0,
    CLI_STATUS        CHAR(2)       NOT NULL,
    CLI_SCORE_BURO    SMALLINT      DEFAULT 0,
    PRIMARY KEY (CLI_ID)
);

CREATE TABLE CREDPROD.CREDITOS (
    CRED_NUM          DECIMAL(10,0) NOT NULL,
    CRED_CLIENTE      DECIMAL(10,0) NOT NULL,
    CRED_MONTO        DECIMAL(15,2) NOT NULL,
    CRED_TASA         DECIMAL(9,6)  NOT NULL,
    CRED_TIPO         CHAR(2)       NOT NULL,
    CRED_STATUS       CHAR(2)       NOT NULL,
    CRED_FECHA_APR    DATE,
    CRED_FECHA_VEN    DATE,
    CRED_PLAZO_MESES  SMALLINT,
    PRIMARY KEY (CRED_NUM),
    FOREIGN KEY (CRED_CLIENTE) REFERENCES CREDPROD.CLIENTES (CLI_ID)
);

CREATE TABLE CREDPROD.LIMITES_CREDITO (
    LIM_TIPO          CHAR(2)       NOT NULL,
    LIM_MAXIMO        DECIMAL(15,2) NOT NULL,
    LIM_MINIMO        DECIMAL(15,2) NOT NULL,
    LIM_VIGENTE       CHAR(1)       DEFAULT 'S',
    PRIMARY KEY (LIM_TIPO)
);

-- NOTA: HIST_ANIO se almacena con 2 digitos (defecto plantado: ventana de siglo)
CREATE TABLE CREDPROD.HISTORIAL_PAGOS (
    HIST_CRED         DECIMAL(10,0) NOT NULL,
    HIST_ANIO         SMALLINT      NOT NULL,
    HIST_MES          SMALLINT      NOT NULL,
    HIST_MONTO_PAGO   DECIMAL(15,2) NOT NULL,
    HIST_ATRASO_DIAS  SMALLINT      DEFAULT 0,
    FOREIGN KEY (HIST_CRED) REFERENCES CREDPROD.CREDITOS (CRED_NUM)
);