CREATE PROCEDURE "informix".sp_trans_hist_revtasa(P_EMPRESA          VARCHAR(3),
       P_FECHA_HOY        DATE
      ) RETURNING VARCHAR(6), VARCHAR(80);

DEFINE  P_COD_RET  VARCHAR(6);
DEFINE  P_MENSAJE  VARCHAR(80);

DEFINE  SQL_ERR          INTEGER;
DEFINE  ISAM_ERR         INTEGER;
DEFINE  ERROR_INFO       VARCHAR(80);

BEGIN
  ON EXCEPTION SET SQL_ERR, ISAM_ERR, ERROR_INFO
     LET P_COD_RET  = SQL_ERR;
     LET P_MENSAJE  = ERROR_INFO;
     RETURN P_COD_RET, P_MENSAJE;
  END EXCEPTION;
  
  LET P_COD_RET = '00000';
  LET P_MENSAJE = 'PROCESO EXITOSO';
  
  BEGIN WORK;
    INSERT INTO SD_REVTASA_HIST
            (EMPRESA,              NUM_CREDITO,
             FECHA_FIN_TASA,       TASA_INTERES,
             TASA_MORATORIOS)
      SELECT M.EMPRESA,             M.NUM_CREDITO,
             R.FECHA_PROX_REV - 1,  M.TASA_INTERES,
             M.TASA_MORATORIOS
      FROM   SD_MAECRED M,
             SD_REVTASA R
      WHERE  M.EMPRESA          = R.EMPRESA
      AND    M.NUM_CREDITO      = R.NUM_CREDITO
      AND    M.TASA_FIJA_O_VAR  = '2'
      AND    SUBSTR(M.STATUS_CRED, 1, 1) NOT IN ('C', 'F', 'O')
      AND    M.BANDERA_MINISTRA = 'M'
      AND    R.FECHA_PROX_REV   = P_FECHA_HOY
      AND    R.EMPRESA          = P_EMPRESA;
  COMMIT WORK;
  RETURN P_COD_RET, P_MENSAJE;
END;
END PROCEDURE;