CREATE PROCEDURE "informix".pagos_nivelados(P_EMPRESA      VARCHAR(3)
                ,P_NUM_CREDITO  VARCHAR(20)
                ,P_FECHA_CUOTA  DATE
                ) RETURNING VARCHAR(5), VARCHAR(80);

DEFINE P_COD_RET            VARCHAR(5);
DEFINE P_MENSAJE            VARCHAR(80);

DEFINE V_NUM_PAGOS          INTEGER;
DEFINE V_TASA               DECIMAL(18,2);
DEFINE V_FACTOR             DECIMAL(8,6);
DEFINE V_ELEVADO            DECIMAL(8,6);
DEFINE V_ELEVADO1           DECIMAL(8,6);
DEFINE V_MTO_PERIODO        DECIMAL(18,2);
DEFINE V_PERIODO            INTEGER;
DEFINE V_PER_TASA           DECIMAL(9,6);
DEFINE V_MTO_SOLICITADO     DECIMAL(18,2);
DEFINE V_INTERES            DECIMAL(18,2);
DEFINE V_MONTO_CUOTA        DECIMAL(18,2);
DEFINE V_FECHA_CUOTA        DATE;
DEFINE V_NUM_REG            INTEGER;
DEFINE v_equival_cap        INTEGER;

DEFINE V_VALOR              VARCHAR(200);
DEFINE V_CADENA             VARCHAR(200);
DEFINE V_PRODUCTO           VARCHAR(4);
DEFINE VV_FECHA_CUOTA       DATE;
DEFINE V_FECHA_PIVOTE       DATE;
DEFINE V_SALTO_PER          INTEGER;
DEFINE V_FECHA_FINAL        DATE;
DEFINE V_FECHA_INICIO       DATE;
DEFINE V_FECHA_PRORRATEO    DATE;
DEFINE V_FECHA_PRIMIN       DATE;
DEFINE V_FECHA_INI          DATE;
DEFINE V_DIA_CUOTA          INTEGER;
DEFINE V_DIA_CORTE          VARCHAR(5);
DEFINE V_RANGO_DIAS         INTEGER;
DEFINE V_GRACIA_CAP         INTEGER;

DEFINE V_MONTO             DECIMAL(18,2);
DEFINE V_PERIODO_PAG_CAP   VARCHAR(1);
DEFINE V_PERIODO_PAG_INT   VARCHAR(1);
DEFINE V_TIPO_CALCULO      VARCHAR(2);
DEFINE V_PERIODO_PLAZO     VARCHAR(1);
DEFINE V_PLAZO             INTEGER;
DEFINE V_AJUSTE_DE_CUOTA   VARCHAR(1);
DEFINE V_AJUSTE_VENC_INT   VARCHAR(1);
DEFINE V_CUOTA_CON_DEC     VARCHAR(1);
DEFINE V_TP_GEN_PLANPAGO   VARCHAR(1);

DEFINE V_FECHA_HOY         DATE;

DEFINE V_AJUSTE_VENCIM     VARCHAR(1);
DEFINE V_DEC_CAP           DECIMAL(18,2);
DEFINE V_DEC_INT           DECIMAL(18,2);
DEFINE V_MTO_CAP           DECIMAL(18,2);
DEFINE V_MTO_INT           DECIMAL(18,2);
DEFINE V_SDO_EXIG_INT      DECIMAL(18,2);
DEFINE V_DIF               DECIMAL(18,2);
DEFINE V_TIPCRED           VARCHAR(3);

DEFINE SQL_ERR             INTEGER;
DEFINE ISAM_ERR            INTEGER;
DEFINE ERROR_INFO          VARCHAR(80);
DEFINE v_tpdias            SMALLINT;
DEFINE v_tipprod            CHAR(2);
DEFINE v_tpperiodo         CHAR(1);

BEGIN
  ON EXCEPTION SET SQL_ERR, ISAM_ERR, ERROR_INFO
     LET P_COD_RET = SQL_ERR;
     LET P_MENSAJE = ERROR_INFO;
     RETURN P_COD_RET, P_MENSAJE;
  END EXCEPTION;



  LET P_COD_RET      = '00000';
  LET P_MENSAJE      = 'PROCESO EXITOSO';
  LET V_NUM_REG      = 0;
  LET V_FECHA_PIVOTE = NULL;
  LET V_SDO_EXIG_INT = 0;

  --OBTIENE LA FECHA DEL SISTEMA
  SELECT FECHA_HOY
  INTO V_FECHA_HOY
  FROM SD_FECHAS
  WHERE EMPRESA = P_EMPRESA;

  --SI ES PRODUCTO DE CONSTRUCCION SE GENERA EL PLAN DE PAGOS DE CAPITAL
  SELECT TRIM(VALOR)
  INTO   V_VALOR
  FROM   SD_PARAM
  WHERE  EMPRESA = P_EMPRESA
  AND    COD_PARAM = '53';

  SELECT TRIM(NUM_PRODUCTO)
  INTO   V_PRODUCTO
  FROM   SD_MAECRED
  WHERE  EMPRESA = P_EMPRESA
  AND    NUM_CREDITO = P_NUM_CREDITO;


  -- Determina tipo de producto para asignar tipo de dias del anio
  SELECT cod_tipcred INTO v_tipprod
    FROM sd_definicion
   WHERE num_producto = V_PRODUCTO;

  IF v_tipprod = "01" OR v_tipprod = "04" THEN
	LET v_tpdias = 360;
  ELSE
	LET v_tpdias = 360;
  END IF

LET P_MENSAJE = V_PRODUCTO;

  --ACTUALIZA EL TIPO DE CALCULO A 02
  UPDATE SD_MAECRED SET TIPO_CALCULO = '02'
  WHERE NUM_CREDITO = P_NUM_CREDITO
  AND EMPRESA = P_EMPRESA;

  IF V_CADENA <> (',' || V_VALOR || ',') THEN --ES UN PRODUCTO DE CONSTRUCCION

    SELECT MIN(FECHA_CUOTA)
    INTO   V_FECHA_PIVOTE
    FROM   SD_PAGINTER
    WHERE  FECHA_CUOTA  >= P_FECHA_CUOTA
    AND    EMPRESA      = P_EMPRESA
    AND    NUM_CREDITO  = P_NUM_CREDITO;

    SELECT COUNT(*)
    INTO   V_SALTO_PER
    FROM   SD_PAGINTER
    WHERE  FECHA_CUOTA  < P_FECHA_CUOTA
    AND    EMPRESA      = P_EMPRESA
    AND    NUM_CREDITO  = P_NUM_CREDITO;

    --SELECCIONA LOS DATOS DEL CREDITO
    SELECT MSDO.MONTO_OTORGADO,  SOL.PERIODO_PAG_INT, SOL.TIPO_CALCULO,
           SOL.PERIODO_PLAZO,    SOL.PLAZO,           SOL.AJUSTE_DE_CUOTA,
           SOL.AJUSTE_VENC_INT,  SOL.CUOTA_CON_DEC,   SOL.TP_GEN_PLANPAGO,
           SOL.GRACIA_CAP,       PCAP.EQUIVALENCIA_DIAS
    INTO   V_MONTO,              V_PERIODO_PAG_INT,   V_TIPO_CALCULO,
           V_PERIODO_PLAZO,      V_PLAZO,             V_AJUSTE_DE_CUOTA,
           V_AJUSTE_VENC_INT,    V_CUOTA_CON_DEC,     V_TP_GEN_PLANPAGO,
           V_GRACIA_CAP,         v_equival_cap
    FROM   BDISOLIC:SS_SOLICITUDES SOL, SD_CODPCAP PCAP, SD_CODPINT PINT, SD_MAESDOS MSDO
    WHERE  MSDO.NUM_CREDITO = P_NUM_CREDITO
    AND    MSDO.EMPRESA = SOL.EMPRESA
    AND    PINT.PERIOD_PAG_INT = SOL.PERIODO_PAG_INT
    AND    PINT.EMPRESA = SOL.EMPRESA
    AND    PCAP.PERIOD_PAGO_CAP = SOL.PERIODO_PAG_CAP
    AND    PCAP.EMPRESA = SOL.EMPRESA
    AND    SOL.EMPRESA = P_EMPRESA
    AND    SOL.NUM_SOLICITUD = P_NUM_CREDITO;

    IF V_TP_GEN_PLANPAGO = 1 THEN
       SELECT FECHA_APERTURA
       INTO   V_FECHA_INICIO
       FROM   SD_MAECRED
       WHERE  NUM_CREDITO = P_NUM_CREDITO
       AND    EMPRESA = P_EMPRESA;
    ELSE
       SELECT MIN(FECHA_CUOTA)
       INTO   V_FECHA_INICIO
       FROM   SD_PAGINTER
       WHERE  NUM_CREDITO = P_NUM_CREDITO
       AND    EMPRESA = P_EMPRESA;
    END IF;

    IF V_FECHA_INICIO < V_FECHA_HOY THEN
       LET V_FECHA_INICIO = V_FECHA_HOY;
    END IF;

    EXECUTE PROCEDURE SP_CALCULA_FECHA(P_EMPRESA,V_GRACIA_CAP,'M',V_FECHA_INICIO
                                      ,'N', V_AJUSTE_VENC_INT)
                 INTO P_COD_RET, P_MENSAJE, V_FECHA_PRORRATEO;

    IF V_FECHA_PRORRATEO > V_FECHA_INICIO THEN
       LET V_FECHA_INICIO = V_FECHA_PRORRATEO;
    ELSE
       LET V_FECHA_PRORRATEO = NULL;
    END IF;

    SELECT DIA_CUOTA
    INTO   V_DIA_CUOTA
    FROM   SD_DEFINICION
    WHERE  NUM_PRODUCTO = V_PRODUCTO
    AND    EMPRESA = P_EMPRESA;

    IF V_PERIODO_PAG_INT <> "1" THEN
       SELECT V_EQUIVAL_CAP*(VALOR/100)
         INTO   V_RANGO_DIAS
         FROM SD_PARAM
        WHERE COD_PARAM = '52'
          AND EMPRESA = P_EMPRESA;
    END IF

    IF V_DIA_CUOTA > 0 AND V_DIA_CUOTA <= 28 THEN
      LET V_FECHA_INI = MDY(MONTH(V_FECHA_INICIO),V_DIA_CUOTA,YEAR(V_FECHA_INICIO));
      IF DAY(V_FECHA_INICIO) >= V_DIA_CUOTA THEN
        EXECUTE PROCEDURE SP_CALCULA_FECHA(P_EMPRESA,1,V_PERIODO_PLAZO,V_FECHA_INI
                                          ,'N', V_AJUSTE_VENC_INT)
                     INTO P_COD_RET, P_MENSAJE, V_FECHA_INICIO;
      ELSE
        IF (V_FECHA_INI - V_FECHA_INICIO) < V_RANGO_DIAS THEN
          EXECUTE PROCEDURE SP_CALCULA_FECHA(P_EMPRESA,1,V_PERIODO_PLAZO,V_FECHA_INI
                                            ,'N', V_AJUSTE_VENC_INT)
                       INTO P_COD_RET, P_MENSAJE, V_FECHA_INICIO;
        ELSE
          LET V_FECHA_INICIO = V_FECHA_INI;
        END IF;
      END IF;
      LET V_DIA_CORTE = 50;
    ELIF V_DIA_CUOTA = 50 THEN
      IF (V_FECHA_INICIO - V_FECHA_HOY)  < V_RANGO_DIAS THEN
         EXECUTE PROCEDURE SP_CALCULA_FECHA(P_EMPRESA,1,V_PERIODO_PLAZO,V_FECHA_INICIO
                                           ,'N', V_AJUSTE_VENC_INT)
                      INTO P_COD_RET, P_MENSAJE, V_FECHA_INICIO;
      END IF;
      LET V_DIA_CORTE = 50;
    ELIF V_DIA_CUOTA = 99 THEN
      IF MONTH(V_FECHA_INICIO) = 12 THEN
         LET V_FECHA_INI = MDY(31,12,YEAR(V_FECHA_INICIO));
      ELSE
         LET V_FECHA_INI = MDY(MONTH(V_FECHA_INICIO)+1,1,YEAR(V_FECHA_INICIO))-1;
      END IF;
      IF (V_FECHA_INI - V_FECHA_INICIO) < V_RANGO_DIAS THEN
         LET V_FECHA_INICIO = V_FECHA_INI;
         EXECUTE PROCEDURE SP_CALCULA_FECHA(P_EMPRESA,1,V_PERIODO_PLAZO,V_FECHA_INICIO
                                           ,'N', V_AJUSTE_VENC_INT)
                      INTO P_COD_RET, P_MENSAJE, V_FECHA_INICIO;
      ELSE
         LET V_FECHA_INICIO = V_FECHA_INI;
      END IF;
      LET V_DIA_CORTE = 99;
    ELIF V_DIA_CUOTA = 15 AND V_PERIODO_PLAZO = 'Q' THEN
      EXECUTE PROCEDURE SP_CALCULA_FECHA(P_EMPRESA,1,V_PERIODO_PLAZO,V_FECHA_INI
                                        ,'N', V_AJUSTE_VENC_INT)
                   INTO P_COD_RET, P_MENSAJE, V_FECHA_INICIO;
      LET V_DIA_CORTE = 50;
    END IF;

    IF V_PERIODO_PAG_INT <> "1" THEN
       EXECUTE PROCEDURE SP_CALCULA_FECHA(P_EMPRESA,V_PLAZO - 1,
					  V_PERIODO_PLAZO, V_FECHA_INICIO,'N',
					  V_AJUSTE_VENC_INT)
          INTO P_COD_RET, P_MENSAJE, V_FECHA_FINAL;
    ELSE
       EXECUTE PROCEDURE SP_CALCULA_FECHA(P_EMPRESA,V_PLAZO,V_PERIODO_PLAZO,
					  V_FECHA_INICIO,'N', V_AJUSTE_VENC_INT)
          INTO P_COD_RET, P_MENSAJE, V_FECHA_FINAL;
    END IF

    UPDATE sd_maecred SET fecha_vencim = V_FECHA_FINAL
     WHERE num_credito = P_NUM_CREDITO
       AND empresa = P_EMPRESA;

    EXECUTE PROCEDURE INTERES(P_EMPRESA
                             ,P_NUM_CREDITO
                             ,V_FECHA_INICIO
                             ,V_FECHA_FINAL
                             ,V_MONTO
                             ,V_PERIODO_PAG_INT
                             ,V_CUOTA_CON_DEC
                             ,V_AJUSTE_VENC_INT
                             ,V_AJUSTE_DE_CUOTA
                             ,V_TIPO_CALCULO
                             ,V_DIA_CORTE
                             ,NULL
                             )
                      INTO  P_COD_RET, P_MENSAJE;

    DELETE FROM SD_PAGOCAPIT
    WHERE EMPRESA = P_EMPRESA
    AND NUM_CREDITO = P_NUM_CREDITO;

    FOREACH SELECT FECHA_CUOTA
            INTO   VV_FECHA_CUOTA
            FROM   SD_PAGINTER
            WHERE  EMPRESA = P_EMPRESA
            AND    NUM_CREDITO = P_NUM_CREDITO
            AND    FECHA_CUOTA >= V_FECHA_PIVOTE
            ORDER BY FECHA_CUOTA

      INSERT INTO SD_PAGOCAPIT VALUES
             (P_EMPRESA, P_NUM_CREDITO, VV_FECHA_CUOTA,1,0,0,0,0,0,'',0,0,'',
              0,1,0,0,'M',1
             );
    END FOREACH;
  END IF;

  IF V_CADENA = (',' || V_VALOR || ',' ) THEN
     SELECT v_tpdias/A.EQUIVALENCIA_DIAS, B.TASA_INTERES, C.MONTO_OTORGADO,
	    A.period_pago_cap
     INTO   V_PER_TASA, V_TASA, V_MTO_SOLICITADO, v_tpperiodo
     FROM   SD_CODPCAP A, SD_MAECRED B, SD_MAESDOS C
     WHERE  A.PERIOD_PAGO_CAP = B.PERIOD_PAGO_CAP
     AND    A.EMPRESA     = B.EMPRESA
     AND    C.EMPRESA     = B.EMPRESA
     AND    C.NUM_CREDITO = B.NUM_CREDITO
     AND    B.EMPRESA     = P_EMPRESA
     AND    B.NUM_CREDITO = P_NUM_CREDITO;

     SELECT COUNT(*)
     INTO   V_NUM_PAGOS
     FROM   SD_PAGINTER
     WHERE  NUM_CREDITO  = P_NUM_CREDITO
     AND    EMPRESA      = P_EMPRESA;
  ELSE
     SELECT v_tpdias/A.EQUIVALENCIA_DIAS, B.TASA_INTERES, C.MONTO_OTORGADO,
            C.SDO_EXIG_INT, A.period_pago_cap
     INTO   V_PER_TASA, V_TASA, V_MTO_SOLICITADO, V_SDO_EXIG_INT, v_tpperiodo
     FROM   SD_CODPCAP A, SD_MAECRED B, SD_MAESDOS C
     WHERE  A.PERIOD_PAGO_CAP = B.PERIOD_PAGO_CAP
     AND    A.EMPRESA     = B.EMPRESA
     AND    C.EMPRESA     = B.EMPRESA
     AND    C.NUM_CREDITO = B.NUM_CREDITO
     AND    B.EMPRESA     = P_EMPRESA
     AND    B.NUM_CREDITO = P_NUM_CREDITO;

     SELECT COUNT(*)
     INTO   V_NUM_PAGOS
     FROM   SD_PAGINTER
     WHERE  FECHA_CUOTA >= V_FECHA_PIVOTE
     AND    NUM_CREDITO  = P_NUM_CREDITO
     AND    EMPRESA      = P_EMPRESA;

     UPDATE SD_MAECRED SET TIPO_CALCULO = '01'
     WHERE  NUM_CREDITO  = P_NUM_CREDITO
     AND    EMPRESA      = P_EMPRESA;

  END IF;

  IF v_tpperiodo = "7" THEN
     SELECT v_tpdias/(fecha_vencim - fecha_apertura)
       INTO V_PER_TASA
       FROM bdicred:sd_maecred
      WHERE num_credito = P_NUM_CREDITO
        AND empresa = P_EMPRESA;
  END IF

  --EFECTUA LA NIVELACION DE PAGOS
  LET V_FACTOR      = ROUND(((V_TASA/100)/V_PER_TASA)+1,8);
  LET V_ELEVADO     = ROUND(POW(V_FACTOR, V_NUM_PAGOS),8);
  IF V_ELEVADO = 1 THEN
    LET V_MTO_PERIODO = V_MTO_SOLICITADO/V_NUM_PAGOS;
  ELSE
    LET V_MTO_PERIODO = ROUND(((V_ELEVADO * V_MTO_SOLICITADO) * (V_FACTOR - 1)) / (V_ELEVADO - 1),2);
  END IF;

  --verifica que tipo de ajuste de importes se debe realizar
  SELECT CUOTA_CON_DEC, AJUSTE_VENCIM
  INTO V_CUOTA_CON_DEC, V_AJUSTE_VENCIM
  FROM BDISOLIC:SS_SOLICITUDES
  WHERE EMPRESA = P_EMPRESA
  AND NUM_SOLICITUD = P_NUM_CREDITO;

  --verifica que solo los tipo de credito 01 y 04 tengan decimales
  select cod_tipcred into v_tipcred
  from sd_definicion where num_producto = v_producto and empresa = p_empresa;

--  IF V_CUOTA_CON_DEC = 'N' THEN-
--    LET V_MTO_PERIODO = TRUNC(V_MTO_PERIODO);
--  END IF;

--    LET V_DIF = V_MTO_PERIODO - TRUNC(V_MTO_PERIODO);
--    LET V_DIF = 1.00 - V_DIF;
--    LET V_MTO_PERIODO = V_MTO_PERIODO + V_DIF;

  IF V_TIPCRED = '01' OR V_TIPCRED = '04' THEN
    LET V_MTO_PERIODO = V_MTO_PERIODO;
  ELSE
    LET V_MTO_PERIODO = ROUND(V_MTO_PERIODO);
  END IF;

  FOREACH SELECT FECHA_CUOTA, MONTO_CUOTA
          INTO   V_FECHA_CUOTA, V_MONTO_CUOTA
          FROM   SD_PAGOCAPIT
          WHERE  FECHA_CUOTA >= NVL(V_FECHA_PIVOTE,FECHA_CUOTA)
          AND    NUM_CREDITO = P_NUM_CREDITO
          AND    EMPRESA     = P_EMPRESA
          ORDER BY FECHA_CUOTA

    LET V_NUM_REG = V_NUM_REG + 1;
    LET V_INTERES = ROUND(V_MTO_SOLICITADO * (V_FACTOR - 1),1);

    IF V_NUM_REG = V_NUM_PAGOS THEN
       UPDATE SD_PAGOCAPIT
       SET    MONTO_CUOTA = V_MTO_SOLICITADO
       WHERE  FECHA_CUOTA = V_FECHA_CUOTA
       AND    NUM_CREDITO = P_NUM_CREDITO
       AND    EMPRESA     = P_EMPRESA;
    ELSE
       UPDATE SD_PAGOCAPIT
       SET    MONTO_CUOTA = V_MTO_PERIODO - V_INTERES
       WHERE  FECHA_CUOTA = V_FECHA_CUOTA
       AND    NUM_CREDITO = P_NUM_CREDITO
       AND    EMPRESA     = P_EMPRESA;
    END IF;

    UPDATE SD_PAGINTER
    SET    MONTO_CUOTA = V_INTERES
    WHERE  FECHA_CUOTA  = V_FECHA_CUOTA
    AND    NUM_CREDITO  = P_NUM_CREDITO
    AND    EMPRESA      = P_EMPRESA;

    LET V_MTO_SOLICITADO = V_MTO_SOLICITADO - (V_MTO_PERIODO - V_INTERES);
  END FOREACH;

  --ACTUALIZA LA PRIMER CUOTA DE INTERES CON EL SALDO QUE TRAE EN SD_EXIG_INT
  --PARA EL CASO DE CONTRICCION PARA LOS OTROS LES SUMA CERO
  UPDATE SD_PAGINTER
  SET MONTO_CUOTA = NVL(MONTO_CUOTA,0) + V_SDO_EXIG_INT
  WHERE NUM_CREDITO = P_NUM_CREDITO
  AND EMPRESA = P_EMPRESA
  AND FECHA_CUOTA = (SELECT MIN(FECHA_CUOTA)
                     FROM SD_PAGOCAPIT
                     WHERE NUM_CREDITO = P_NUM_CREDITO
                     AND EMPRESA = P_EMPRESA);

  --Actualiza el saldo_no_exig de sd_maesdos
  update sd_maesdos
  set   sdo_no_exig = sdo_no_exig + (select sum(monto_cuota)
                                     from sd_paginter
                                     where num_credito = sd_maesdos.num_credito
                                     and empresa = sd_maesdos.empresa)
  where num_credito = p_num_credito
  and empresa = p_empresa;

  RETURN P_COD_RET, P_MENSAJE;
END;
END PROCEDURE;