CREATE PROCEDURE "informix".sp_genera_movdia(P_EMPRESA		VARCHAR(3),
      P_NUM_CREDITO	VARCHAR(20),
      P_EJECUTIVO       VARCHAR(8),
      P_PRODUCTO        LIKE SD_MAECRED.NUM_PRODUCTO,
      P_SUCURSAL        LIKE SD_MAECRED.SUCURSAL,
      P_DIVISA          LIKE SD_MAECRED.DIVISA ,
      P_FECHA_MOV       DATE,
      P_FUNCION         VARCHAR(5),
      P_MONTO           DECIMAL(18,2)
     )RETURNING VARCHAR(6), VARCHAR(80);

DEFINE  P_COD_RET  VARCHAR(6);
DEFINE  P_MENSAJE  VARCHAR(80);

DEFINE  V_PORCENT_PART  LIKE SD_FUENTES_X_CRED.PORCENT_PART;
DEFINE  V_TASA_FONDO    LIKE SD_FUENTES_X_CRED.TASA_FONDO;
DEFINE  V_CODIGO_REF    LIKE SD_TRANSFUN.CODIGO_REF;
DEFINE  V_CODIGO_INS    LIKE SD_FUENTES_X_CRED.CODIGO_INS;
DEFINE  V_INDIC_PROPIO  LIKE SD_FUENTES_X_CRED.INDIC_PROPIO;

DEFINE  V_CONTADOR      INTEGER;
DEFINE  V_CONT          VARCHAR(10);
DEFINE  V_FOLIO         VARCHAR(16);
DEFINE  V_PARTICIP      DECIMAL(18,2);
DEFINE  V_MONTO         DECIMAL(18,2);
DEFINE  V_TRANSACC_SUC  VARCHAR(4);
DEFINE  V_REF           INTEGER;

DEFINE  SQL_ERR          INTEGER;
DEFINE  ISAM_ERR         INTEGER;
DEFINE  ERROR_INFO       VARCHAR(80);

BEGIN
  ON EXCEPTION SET SQL_ERR, ISAM_ERR, ERROR_INFO
     LET P_COD_RET  = SQL_ERR;
     LET P_MENSAJE  = ERROR_INFO;
     RETURN P_COD_RET, P_MENSAJE;
  END EXCEPTION;

      LET P_COD_RET      = '00000';
      LET P_MENSAJE      = 'PROCESO EXITOSO';
      LET V_MONTO        = P_MONTO;
      LET V_CONTADOR     = 0;
      LET V_TRANSACC_SUC = '0000';
      LET V_REF = NULL;

      FOREACH SELECT F.PORCENT_PART, F.TASA_FONDO, T.CODIGO_REF, F.CODIGO_INS, F.INDIC_PROPIO
              INTO   V_PORCENT_PART, V_TASA_FONDO, V_CODIGO_REF, V_CODIGO_INS, V_INDIC_PROPIO
              FROM   OUTER SD_TRANSFUN T, SD_FUENTES_X_CRED F
              WHERE F.EMPRESA       = T.EMPRESA
              AND   F.CODIGO_INS    = T.CODIGO_INS
              AND   F.EMPRESA       = P_EMPRESA
              AND   F.NUM_CREDITO   = P_NUM_CREDITO
              AND   T.CODIGO_FUN    = P_FUNCION
              ORDER BY INDIC_PROPIO

         IF V_CODIGO_REF IS NULL OR V_CODIGO_REF = '' THEN
            BEGIN
              ON EXCEPTION SET SQL_ERR, ISAM_ERR, ERROR_INFO
                LET P_COD_RET = SQL_ERR;
                LET P_MENSAJE = ERROR_INFO;
                LET V_REF = NULL;
              END EXCEPTION;
                SELECT T.CODIGO_REF
                INTO   V_REF
                FROM   SD_TRANSFUN T
                WHERE  T.CODIGO_FUN = P_FUNCION
                AND    T.CODIGO_INS IS NULL
                AND    T.EMPRESA    = P_EMPRESA;
            END;
         ELSE
            LET V_REF = V_CODIGO_REF;
         END IF;
         IF P_COD_RET = '00000' THEN
            IF V_REF IS NULL THEN
              LET P_COD_RET = '956';
              LET P_MENSAJE = 'CODIGO DE REFERENCIA EN SD_TRANSFUN NO VALIDO';
              RETURN P_COD_RET, P_MENSAJE;
            ELSE
              LET V_CONTADOR = V_CONTADOR + 1;
              LET V_CONT     = LPAD(V_CONTADOR,8,'0');
              LET V_FOLIO    = P_EJECUTIVO || V_CONT;

              IF V_INDIC_PROPIO = 1 THEN
                LET V_PARTICIP = V_MONTO;
              ELSE
                LET V_PARTICIP = (V_MONTO * V_PORCENT_PART)/100;
                LET V_MONTO    =  V_MONTO - V_PARTICIP;
              END IF;
              EXECUTE PROCEDURE GENMOV(P_EMPRESA, P_NUM_CREDITO, P_PRODUCTO, V_REF, P_FUNCION,
                                       P_FECHA_MOV, V_PARTICIP, V_FOLIO, P_SUCURSAL, P_DIVISA,
                                       V_TRANSACC_SUC)
                                  INTO P_COD_RET, P_MENSAJE;
            END IF;
            IF P_COD_RET = '00000' THEN
              RETURN P_COD_RET, P_MENSAJE;
            END IF;
         END IF;
      END FOREACH;
      RETURN P_COD_RET, P_MENSAJE;
END;
END PROCEDURE;