CREATE PROCEDURE "informix".sp_ministracion_automatica(P_EMPRESA VARCHAR(3)
       ) RETURNING VARCHAR(5), VARCHAR(80);

DEFINE P_COD_RET VARCHAR(5);
DEFINE P_MENSAJE VARCHAR(80);

DEFINE V_FECHA_HOY DATE;
DEFINE V_NUM_CREDITO VARCHAR(20);
DEFINE V_FECHA_CUOTA DATE;
DEFINE V_TP_DESEMBOLSO VARCHAR(1);
DEFINE V_MONTO DECIMAL(18,2);

DEFINE  SQL_ERR          INTEGER;
DEFINE  ISAM_ERR         INTEGER;
DEFINE  ERROR_INFO       VARCHAR(80);

BEGIN

  ON EXCEPTION SET SQL_ERR, ISAM_ERR, ERROR_INFO
     LET P_COD_RET  = SQL_ERR;
     LET P_MENSAJE  = ERROR_INFO;
     RETURN P_COD_RET, P_MENSAJE;
  END EXCEPTION;

  LET P_COD_RET = '00000';
  LET P_MENSAJE = 'PROCESO EXITOSO';
  LET V_TP_DESEMBOLSO = '1';

  SELECT FECHA_HOY
  INTO V_FECHA_HOY
  FROM SD_FECHAS
  WHERE EMPRESA = P_EMPRESA;

  FOREACH SELECT NUM_CREDITO, FECHA_PROGRAMADA, MONTO_OTORGADO
          INTO V_NUM_CREDITO, V_FECHA_CUOTA, V_MONTO
          FROM SD_DETMINIS
          WHERE EMPRESA = P_EMPRESA
          AND FECHA_PROGRAMADA = (SELECT MAX(FECHA_PROGRAMADA)
                                  FROM SD_DETMINIS
                                  WHERE EMPRESA = P_EMPRESA
                                  AND STATUS_MINISTRA = 'A'
                                  AND FECHA_PROGRAMADA <= V_FECHA_HOY)

    SELECT NVL(CON_INTEGRANTES,'1')
    INTO V_TP_DESEMBOLSO
    FROM BDISOLIC:SS_SOLICITUDES 
    WHERE EMPRESA = P_EMPRESA
    AND NUM_SOLICITUD = V_NUM_CREDITO;

    EXECUTE PROCEDURE BDICRED:MINISTRACION
                     (P_EMPRESA, V_NUM_CREDITO,V_TP_DESEMBOLSO
                     ,V_FECHA_CUOTA, V_MONTO) INTO P_COD_RET, P_MENSAJE;

    IF P_COD_RET <> '00000' THEN
       RETURN P_COD_RET, P_MENSAJE;
    END IF;

  END FOREACH;

  RETURN P_COD_RET, P_MENSAJE;
END;
END PROCEDURE;