CREATE
PROCEDURE "informix".sp_verif_primerminis( P_EMPRESA                  VARCHAR(3)  ,
              			P_NUM_CREDITO              VARCHAR(20) ,
                                P_FECHA_PROGRAMADA         DATE     ,
              			P_MONTO_OTORGADO           DECIMAL(18,2)
                              )
RETURNING DECIMAL(18,2), VARCHAR(10), VARCHAR(80);
--P_MONTO_FINAL          OUT NUMBER   ,
--P_COD_RET              OUT VARCHAR2 ,
--P_MENSAJE              OUT VARCHAR2 ) IS
--VERIFICA SI ES LA PRIMERA MINISTRACION PARA REALIZAR LAS DEDUCCIONES PERTINENTES

DEFINE V_MONTO_DEDUC   DECIMAL(18,2);
DEFINE V_FECHA_MINIMA  DATE;
DEFINE P_COD_RET       VARCHAR(10);
DEFINE P_MENSAJE       VARCHAR(80);
DEFINE V_MONTO_FINAL   DECIMAL(18,2);

BEGIN
   ON EXCEPTION
      --SIPK_MENSAJES.SP_TRAE_MENSAJE (SQLCODE, SQLERRM, P_COD_RET, P_MENSAJE);
      RETURN 0, P_COD_RET, P_MENSAJE;
   END EXCEPTION;

   LET P_COD_RET = '00000';
   LET P_MENSAJE = 'PROCESO EXITOSO';
   FOREACH DETMINIS FOR SELECT MIN(FECHA_PROGRAMADA) FECHA_MINIMA
                    INTO V_FECHA_MINIMA
                    FROM   SD_DETMINIS
                    WHERE  EMPRESA           = P_EMPRESA
                    AND    FECHA_PROGRAMADA <= P_FECHA_PROGRAMADA
                    AND    NUM_CREDITO       = P_NUM_CREDITO

      IF V_FECHA_MINIMA IS NULL THEN
         LET P_COD_RET = '00001';
         LET P_MENSAJE = 'NO SE CUENTA CON UNA FECHA DE DESEMBOLSO';
         RETURN 0, P_COD_RET, P_MENSAJE;
      END IF;
      IF V_FECHA_MINIMA = P_FECHA_PROGRAMADA THEN
         FOREACH DETCOMI FOR  SELECT NVL(SUM(MONTO_COM),0) MONTO_DEDUC
                              INTO V_MONTO_DEDUC
                              FROM   SD_DETCOMI
                              WHERE  EMPRESA     = P_EMPRESA
                              AND    NUM_CREDITO = P_NUM_CREDITO
            LET V_MONTO_FINAL = V_MONTO_DEDUC;
         END FOREACH; --DETCOMI
      ELSE
         LET V_MONTO_FINAL = 0;
      END IF;
   END FOREACH; --DETMINIS
   RETURN V_MONTO_FINAL, P_COD_RET, P_MENSAJE;
END;
END PROCEDURE;