-- BigQuery DDL - capa BRONZE (raw 1:1, todo STRING, + metadata tecnica)
-- dataset: sap_bronze
CREATE SCHEMA IF NOT EXISTS sap_bronze;

CREATE OR REPLACE TABLE sap_bronze.kna1 (
  MANDT STRING, KUNNR STRING, NAME1 STRING, LAND1 STRING, ORT01 STRING,
  PSTLZ STRING, KTOKD STRING, LOEKZ STRING, ERDAT STRING,
  _ingest_ts TIMESTAMP, _source_system STRING, _batch_id STRING);

CREATE OR REPLACE TABLE sap_bronze.mara (
  MANDT STRING, MATNR STRING, MTART STRING, MATKL STRING, MEINS STRING,
  LVORM STRING, ERSDA STRING,
  _ingest_ts TIMESTAMP, _source_system STRING, _batch_id STRING);

CREATE OR REPLACE TABLE sap_bronze.makt (
  MANDT STRING, MATNR STRING, SPRAS STRING, MAKTX STRING,
  _ingest_ts TIMESTAMP, _source_system STRING, _batch_id STRING);

CREATE OR REPLACE TABLE sap_bronze.tcurx (
  CURRKEY STRING, CURRDEC STRING,
  _ingest_ts TIMESTAMP, _source_system STRING, _batch_id STRING);

CREATE OR REPLACE TABLE sap_bronze.vbak (
  MANDT STRING, VBELN STRING, ERDAT STRING, KUNNR STRING, NETWR STRING,
  WAERK STRING, VKORG STRING, AUART STRING, VBTYP STRING,
  _ingest_ts TIMESTAMP, _source_system STRING, _batch_id STRING);

CREATE OR REPLACE TABLE sap_bronze.vbap (
  MANDT STRING, VBELN STRING, POSNR STRING, MATNR STRING, KWMENG STRING,
  NETWR STRING, WAERK STRING, MEINS STRING,
  _ingest_ts TIMESTAMP, _source_system STRING, _batch_id STRING);
