CREATE PROCEDURE "informix".sp_actualiza_escrow()
       RETURNING VARCHAR(5)

DEFINE P_COD_RET       VARCHAR(5);
DEFINE V_NUM_CREDITO   VARCHAR(20);
DEFINE V_COD_COMIS     VARCHAR(20);
DEFINE V_MONTO_COM     DECIMAL(18,2);
DEFINE V_MONTO_MEN     DECIMAL(18,2);
DEFINE V_FECHA_CUOTA   DATE;
DEFINE V_STATUS_CUOTA  VARCHAR(3);
DEFINE V_EXISTE        INTEGER;

BEGIN
  LET V_EXISTE = 1;
  LET P_COD_RET = '00000';

  FOREACH 
     SELECT A.NUM_CREDITO, A.COD_COMIS, B.FECHA_CUOTA, B.STATUS_CUOTA
           ,NVL(A.MONTO_POLIZA,0), NVL(A.MONTO_MENSUAL,0)
     INTO   V_NUM_CREDITO, V_COD_COMIS, V_FECHA_CUOTA, V_STATUS_CUOTA
           ,V_MONTO_COM, V_MONTO_MEN
     FROM   SD_ESCROW A, SD_PAGOCAPIT B
     WHERE  1 = 1
     AND A.NUM_CREDITO = B.NUM_CREDITO
     AND A.empresa = B.EMPRESA
     AND B.STATUS_CUOTA IN ('2','7')
     AND B.FECHA_CUOTA < '02/02/2004'
     ORDER BY 1,2,3

    LET V_EXISTE = 1;

    SELECT COUNT(*) INTO V_EXISTE FROM SD_DETCOMI
    WHERE FECHA_ALTA  = V_FECHA_CUOTA
    AND   COD_COMIS   = V_COD_COMIS
    AND   NUM_CREDITO = V_NUM_CREDITO;

    IF V_EXISTE = 0 THEN
       INSERT INTO SD_DETCOMI VALUES 
       ('001',V_COD_COMIS,V_NUM_CREDITO, V_FECHA_CUOTA, ''
       ,V_MONTO_COM, V_MONTO_MEN,0,'P','','informix','02/01/2004');
    END IF;
   
  END FOREACH;

  RETURN P_COD_RET;
END;
END PROCEDURE;