CREATE PROCEDURE "informix".sp_inicializa_acum_prov_normal(P_EMPRESA		VARCHAR(3),
      P_NUM_CREDITO	VARCHAR(20)
     ) RETURNING VARCHAR(5), VARCHAR(80);

DEFINE P_COD_RET         VARCHAR(3);
DEFINE P_MENSAJE         VARCHAR(80);

DEFINE  SQL_ERR          INTEGER;
DEFINE  ISAM_ERR         INTEGER;
DEFINE  ERROR_INFO       VARCHAR(80);

BEGIN
  ON EXCEPTION SET SQL_ERR, ISAM_ERR, ERROR_INFO
     LET P_COD_RET  = SQL_ERR;
     LET P_MENSAJE  = ERROR_INFO;
     RETURN P_COD_RET, P_MENSAJE;
  END EXCEPTION;

  LET P_COD_RET = '00000';
  LET P_MENSAJE = 'PROCESO EXITOSO';

      UPDATE SD_MAESDOS
      SET    PROVISION_NORMAL = 0
      WHERE  NUM_CREDITO = P_NUM_CREDITO
      AND    EMPRESA	 = P_EMPRESA;

  RETURN P_COD_RET, P_MENSAJE;
END;
END PROCEDURE;