CREATE PROCEDURE "informix".sp_provision(P_EMPRESA         VARCHAR(3),
      P_NUM_CREDITO     VARCHAR(20),
      P_EJECUTIVO       VARCHAR(8),
      P_PRODUCTO        VARCHAR(4),
      P_SUCURSAL        VARCHAR(4),
      P_DIVISA          VARCHAR(4),
      P_DIAS_CALCULO    INTEGER,
      P_FECHA_MOV       DATE,
      P_FUNCION         VARCHAR(4),
      P_INT_DIARIO      DECIMAL(18,2),
      P_SDO_CAPITAL     DECIMAL(18,2),
      P_CAMBIO_MES      VARCHAR(3),
      P_ACUM_PROVNOR    VARCHAR(3),
      P_INI_PERIODO     VARCHAR(3),
      P_TIPO_CALCULO    VARCHAR(3),
      P_DIAS_PROV       INTEGER
     ) RETURNING VARCHAR(5), VARCHAR(80);

DEFINE P_COD_RET       VARCHAR(5);
DEFINE P_MENSAJE       VARCHAR(80);

DEFINE V_MONTO_CUOTA   DECIMAL(18,2);
DEFINE V_INTERES       DECIMAL(18,2);
DEFINE V_REFERENCIA    INTEGER;
DEFINE V_TRANSACC_SUC  VARCHAR(4);
DEFINE V_FOLIO         VARCHAR(16);
DEFINE V_FUNCION_FTE   VARCHAR(3);
DEFINE V_FECHA_CUOTA   DATE;

DEFINE  SQL_ERR        INTEGER;
DEFINE  ISAM_ERR       INTEGER;
DEFINE  ERROR_INFO     VARCHAR(80);

BEGIN

  ON EXCEPTION SET SQL_ERR, ISAM_ERR, ERROR_INFO
     LET P_COD_RET  = SQL_ERR;
     LET P_MENSAJE  = ERROR_INFO;
     RETURN P_COD_RET, P_MENSAJE;
  END EXCEPTION;

--   LET p_dias_calculo = 29;
  LET V_TRANSACC_SUC = '0000';
  LET V_FUNCION_FTE  = '609';
  LET P_COD_RET      = '00000';
  LET V_INTERES      = P_INT_DIARIO * P_DIAS_CALCULO;

  SELECT MIN(PI.FECHA_CUOTA)
  INTO V_FECHA_CUOTA
  FROM  SD_PAGINTER PI
  WHERE PI.NUM_CREDITO  = P_NUM_CREDITO
  AND   PI.EMPRESA      = P_EMPRESA
  AND   PI.STATUS_CUOTA = '1';

  SELECT NVL(MIN(P.MONTO_CUOTA), 0)
  INTO   V_MONTO_CUOTA
  FROM   SD_PAGINTER P
  WHERE  P.NUM_CREDITO = P_NUM_CREDITO
  AND    P.EMPRESA     = P_EMPRESA
  AND    P.FECHA_CUOTA = V_FECHA_CUOTA;

  IF P_TIPO_CALCULO = '01' THEN
    UPDATE SD_MAESDOS
    SET SDO_NO_EXIG      = DECODE( P_INI_PERIODO, 'S'
                                 , SDO_NO_EXIG + V_INTERES + V_MONTO_CUOTA
                                 , SDO_NO_EXIG + V_INTERES)
      , SDO_ACUM_INTPER  = DECODE(P_INI_PERIODO, 'S'
                                 ,V_INTERES
                                 ,SDO_ACUM_INTPER + V_INTERES)
      , PROVISION_NORMAL = DECODE(P_ACUM_PROVNOR,'S'
                                 ,PROVISION_NORMAL + V_INTERES
                                 ,V_INTERES)
      , SDO_MES_ANT_INT  = DECODE(P_CAMBIO_MES,'S'
                                 ,SDO_ACUM_MES_INT
                                 ,SDO_MES_ANT_INT)
      , SDO_ACUM_MES_INT = DECODE(P_CAMBIO_MES,'S'
                                 ,V_INTERES
                                 ,SDO_ACUM_MES_INT + V_INTERES)
      , DIAS_ACUM_INT    = DIAS_ACUM_INT + P_DIAS_PROV
      , DIAS_ACUM_INTPER = DECODE(P_INI_PERIODO,'S'
                                 ,P_DIAS_PROV
                                 ,NVL(DIAS_ACUM_INTPER,0) + P_DIAS_PROV)
    WHERE  NUM_CREDITO = P_NUM_CREDITO
    AND    EMPRESA = P_EMPRESA;

    UPDATE SD_PAGINTER
    SET    MONTO_CUOTA = NVL(MONTO_CUOTA,0) + V_INTERES
          ,MONTO_FINANCIADO = NVL(MONTO_FINANCIADO,0) + V_INTERES
    WHERE  NUM_CREDITO = P_NUM_CREDITO
    AND    EMPRESA = P_EMPRESA
    AND    FECHA_CUOTA = V_FECHA_CUOTA;

  ELSE
    UPDATE SD_MAESDOS
    SET SDO_ACUM_INTPER  = DECODE(P_INI_PERIODO, 'S'
                                 ,V_INTERES
                                 ,SDO_ACUM_INTPER + V_INTERES)
      , PROVISION_NORMAL = DECODE(P_ACUM_PROVNOR,'S'
                                 ,PROVISION_NORMAL + V_INTERES
                                 ,V_INTERES)
      , SDO_MES_ANT_INT  = DECODE(P_CAMBIO_MES,'S'
                                 ,SDO_ACUM_MES_INT
                                 ,SDO_MES_ANT_INT)
      , SDO_ACUM_MES_INT = DECODE(P_CAMBIO_MES,'S'
                                 ,V_INTERES
                                 ,SDO_ACUM_MES_INT + V_INTERES)
      , DIAS_ACUM_INT    = DIAS_ACUM_INT + P_DIAS_PROV
      , DIAS_ACUM_INTPER = DECODE(P_INI_PERIODO,'S'
                                 ,P_DIAS_PROV
                                 ,NVL(DIAS_ACUM_INTPER,0) + P_DIAS_PROV)
    WHERE  NUM_CREDITO = P_NUM_CREDITO
    AND    EMPRESA = P_EMPRESA;

    UPDATE SD_PAGINTER
    SET    MONTO_FINANCIADO = NVL(MONTO_FINANCIADO,0) + V_INTERES
    WHERE  NUM_CREDITO = P_NUM_CREDITO
    AND    EMPRESA = P_EMPRESA
    AND    FECHA_CUOTA = V_FECHA_CUOTA;

  END IF;

  SELECT MAX(CODIGO_REF)
  INTO   V_REFERENCIA
  FROM   SD_TRANSFUN
  WHERE  EMPRESA    = P_EMPRESA
  AND    CODIGO_FUN = P_FUNCION
  AND    CODIGO_INS = (SELECT VALOR
                       FROM   SD_PARAM
                       WHERE  EMPRESA = P_EMPRESA
                       AND    COD_PARAM  = '40');

  IF V_REFERENCIA IS NULL OR V_REFERENCIA = '' THEN
     LET P_COD_RET = '957';
     LET P_MENSAJE = 'REFERENCIA EN TRASNFUN INVALIDA';
     RETURN P_COD_RET, P_MENSAJE;
  ELSE
     LET V_FOLIO = P_EJECUTIVO || REPLACE(CURRENT HOUR TO FRACTION,':','');
     EXECUTE PROCEDURE GENMOV
         (P_EMPRESA, P_NUM_CREDITO, P_PRODUCTO, V_REFERENCIA, P_FUNCION,
          P_FECHA_MOV, V_INTERES, V_FOLIO, P_SUCURSAL, P_DIVISA, V_TRANSACC_SUC
         ) INTO P_COD_RET, P_MENSAJE;
  END IF;
  RETURN P_COD_RET, P_MENSAJE;
END;
END PROCEDURE;