CREATE PROCEDURE "informix".sp_verifconta(P_EMPRESA     VARCHAR(3) 
      ,P_FECHA_MOV   DATE
      ) RETURNING VARCHAR(5), VARCHAR(80);

DEFINE P_COD_RET   VARCHAR(5);
DEFINE P_MENSAJE   VARCHAR(80);

DEFINE V_NUM_PRODUCTO        VARCHAR(10);
DEFINE V_CODIGO_FUN          VARCHAR(10);
DEFINE V_CODIGO_REF          VARCHAR(10);
DEFINE V_TRANSFUN_TRANSACC   VARCHAR(10);
DEFINE V_PRODTRAN_TRANSACC   VARCHAR(10);

DEFINE V_SE_CONTA            VARCHAR(2);
DEFINE V_EXISTE              INTEGER;

BEGIN
  LET P_COD_RET = '00000';
  LET P_MENSAJE = 'PROCESO EXITOSO';
  LET V_EXISTE  = 1;
  LET V_TRANSFUN_TRANSACC = '';
  LET V_PRODTRAN_TRANSACC = '';

  DELETE FROM SD_VERIF_CONTABILIDAD;

  FOREACH 
     SELECT DISTINCT A.NUM_PRODUCTO,A.CODIGO_FUN, A.CODIGO_REF, NVL(B.TRANSACC,'X')
     INTO   V_NUM_PRODUCTO, V_CODIGO_FUN, V_CODIGO_REF, V_TRANSFUN_TRANSACC
     FROM   SD_MOVDIA A, OUTER SD_TRANSFUN B
     WHERE  B.CODIGO_REF  = A.CODIGO_REF
     AND    B.CODIGO_FUN  = A.CODIGO_FUN
     AND    A.REVERSADO   = 'N'
     AND    A.FECHA_MOV   = P_FECHA_MOV
     AND    A.EMPRESA     = P_EMPRESA
     ORDER BY 2,3,1

     LET V_EXISTE = 1;

     IF V_TRANSFUN_TRANSACC = 'X' THEN
       INSERT INTO SD_VERIF_CONTABILIDAD 
       VALUES ('1',V_NUM_PRODUCTO, V_CODIGO_FUN, V_CODIGO_REF
              ,V_TRANSFUN_TRANSACC,V_PRODTRAN_TRANSACC);
     END IF;

     SELECT NVL(SE_CONTABILIZA,'N')
     INTO   V_SE_CONTA
     FROM   SI_TRANSACC B
     WHERE  NUMERO = TRIM(V_TRANSFUN_TRANSACC)
     AND    SISTEMA = '06'
     AND    EMPRESA = P_EMPRESA;

     IF V_SE_CONTA = 'S' THEN
       SELECT COUNT(*)
       INTO   V_EXISTE
       FROM   SI_PRODTRAN
       WHERE  PRODUCTO     = TRIM(V_NUM_PRODUCTO)
       AND    TRANSACCION  = TRIM(V_TRANSFUN_TRANSACC)
       AND    SISTEMA      = '06'
       AND    EMPRESA      = P_EMPRESA;

       IF V_EXISTE = 0 THEN
         INSERT INTO SD_VERIF_CONTABILIDAD
         VALUES ('2',V_NUM_PRODUCTO, V_CODIGO_FUN, V_CODIGO_REF
                ,'',V_TRANSFUN_TRANSACC);
       END IF;
     END IF;
  END FOREACH;

  RETURN P_COD_RET, P_MENSAJE;

END;
END PROCEDURE;