create procedure "informix".sp_eliminaarchivo(cTipoArchivo CHAR(2), pUsuario CHAR(8),cNomArchivo VARCHAR (20), cArchivoControl VARCHAR (20))
RETURNING  CHAR(6);
--- Definicion de variables
DEFINE vsqlerr                     	INTEGER;
DEFINE cCodRet                     	CHAR(6);
DEFINE sRutaArchivo     			CHAR(30);
DEFINE vsSQLC 		                CHAR (1000);
DEFINE cNombre     					CHAR(20);
DEFINE cNombreControl     			CHAR(20);
DEFINE cNombreAcuseA     			CHAR(20);
DEFINE cNombreAcuseN    			CHAR(20);
DEFINE cPrefijo 					char(2);
DEFINE cPrefijoControl 				char(2);
DEFINE pTipoError                  CHAR(1);
DEFINE pSpLlamado                  CHAR(40);
DEFINE pMostrado                   CHAR(1);
DEFINE cNombreError					CHAR(20);
DEFINE sBanderaError				char(2);
DEFINE cErrorSP						CHAR(6);
DEFINE pMensaje					CHAR(100);
DEFINE cFechaSer                   CHAR(10);
DEFINE vsSQL1C                     CHAR (300);
DEFINE vsSQL2C                     CHAR (400) ;
DEFINE vsSQL3C                     CHAR (150);
DEFINE vIpDest 					   CHAR(30);
DEFINE vUsuarioDestino 			   CHAR(30);
DEFINE cClaveBan                   CHAR(5);
 DEFINE cLetraInicial   CHAR(1);
---inicializacion de variables
LET cCodRet = '';
LET sRutaArchivo = '';
LET  vsSQLC = '';
LET cNombre  = '';
LET cNombreControl  ='';
LET cNombreAcuseN = '';
LET cNombreAcuseA = '';
LET cPrefijoControl = '';
LET cPrefijo = '';
LET pTipoError = '';
LET  pSpLlamado  = '';
LET pMostrado = '';
LET cNombreError = '';
LET sBanderaError = '';
LET cErrorSP = '';
LET pMensaje = '';
LET cFechaSer = '';
LET vsSQL1C = '' ;
LET vsSQL2C = '' ;
LET vsSQL3C = '' ;
LET vIpDest = '';
LET vUsuarioDestino = '';
LET cClaveBan = '';
LET cLetraInicial = '';
  --SET DEBUG FILE TO "/home/informix/eliminaarchivo.out";
	--TRACE ON;
    BEGIN
    ON EXCEPTION  SET vsqlerr
                IF vsqlerr <> 0  THEN
					LET  cCodRet  = vsqlerr;
					LET pTipoError = 'P';
                    LET pSpLLamado = 'sp_generaarchivosat';
                    LET pMostrado = 'N';
							IF (sBanderaError = 2) then
								UPDATE bdilide:sl_archsat SET status = 'E' WHERE nombre_arch = cNombreControl;
                            END IF;
                            --Commit work;
                            execute procedure bdilide:sp_grabarErrores(cNombreError, cCodRet, pTipoError, pSpLLamado, pMensaje, pMostrado)  into cErrorSP;
				LET vsSQLC = '';
				LET vsSQLC = 'rm -f ' || TRIM(sRutaArchivo) ||  trim(cNomArchivo);
				SYSTEM vsSQLC;
				LET vsSQLC = '';
				LET vsSQLC = 'rm -f ' || TRIM(sRutaArchivo) ||  trim(cArchivoControl);
				SYSTEM vsSQLC;
				LET vsSQLC = '';
				LET vsSQLC = 'rm -f ' || TRIM(sRutaArchivo) ||  trim(cNombreControl);
				SYSTEM vsSQLC;
				LET vsSQLC = 'rm -f ' || TRIM(sRutaArchivo) ||  'load_sat_resp.sql';
				SYSTEM vsSQLC;
				LET vsSQLC = '';
				LET vsSQLC = 'rm -f ' || TRIM(sRutaArchivo) ||  'load_archivo_sat.sql';
				SYSTEM vsSQLC;
				LET vsSQLC = '';
				LET vsSQLC = 'rm -f ' || TRIM(sRutaArchivo) ||  'load_control_resp.sql';
				SYSTEM vsSQLC;
				LET vsSQLC = '';
			LET vsSQLC = 'rm -f ' || TRIM(sRutaArchivo) ||  'tmp_SAT_acuse.sql';
			SYSTEM vsSQLC;
                    RETURN cCodRet;
                END IF;
    END  EXCEPTION;
		SELECT TRIM(desc_valor) INTO vIpDest FROM bdilide:sl_parametros WHERE cve_param = '25' and valor = '01';
        SELECT  TRIM(desc_valor) INTO vUsuarioDestino FROM bdilide:sl_parametros WHERE cve_param = '25' and valor = '02';
        SELECT trim(desc_valor) INTO sRutaArchivo      FROM bdilide:sl_parametros WHERE cve_param = '25' and valor = '06';
        SELECT TRIM(desc_valor) INTO cClaveBan  FROM bdilide:sl_parametros WHERE cve_param = '25' AND valor = '07';
		SELECT  fecha_hoy
		INTO cFechaSer
		FROM bdinteg:si_fechas
		WHERE empresa = '001';

		--LET cFechaArc = SUBSTR(cFechaSer,7,10) || SUBSTR(cFechaSer,1,2) || SUBSTR(cFechaSer,4,5);
        IF cTipoArchivo = '01' THEN
				LET cPrefijo = '';
                LET cPrefijo = "CC";
				LET cNombreAcuseA = SUBSTR(cNomArchivo,3,20);
				LET cNombreAcuseA = cPrefijo || TRIM(cNombreAcuseA);
				LET cNombreAcuseA = TRIM(cNombreAcuseA);
                LET cPrefijoControl = '';
				LET cPrefijoControl = 'CT';
				LET cNombreAcuseN = SUBSTR(cNomArchivo,3,20);
				LET cNombreAcuseN = cPrefijoControl || TRIM(cNombreAcuseN);
				LET cNombreAcuseN = TRIM(cNombreAcuseN);
				LET vsSQLC = '';
				LET vsSQLC = 'rm -f ' || TRIM(sRutaArchivo) ||  'tmp_SAT_control.sql';
				SYSTEM vsSQLC;
				LET vsSQLC = '';
				LET vsSQLC = 'rm -f ' || TRIM(sRutaArchivo) ||  'tmp_SAT.sql';
				SYSTEM vsSQLC;
				LET cCodRet = '001';
				LET vsSQLC = '';
				LET vsSQLC = 'rm -f ' || TRIM(sRutaArchivo) ||  trim(cNombreAcuseA);
				SYSTEM vsSQLC;
				LET vsSQLC = '';
				LET vsSQLC = 'rm -f ' || TRIM(sRutaArchivo) ||  trim(cNombreAcuseN);
				SYSTEM vsSQLC;
				return cCodRet;
        END IF;
		IF cTipoArchivo = '02' THEN
                LET cPrefijo = '';
                LET cPrefijo = "RA";
				LET cNombreAcuseA = SUBSTR(cNomArchivo,3,20);
				LET cNombreAcuseA = cPrefijo || TRIM(cNombreAcuseA);
				LET cNombreAcuseA = TRIM(cNombreAcuseA);
                LET cPrefijoControl = '';
				LET cPrefijoControl = 'RN';
				LET cNombreAcuseN = SUBSTR(cNomArchivo,3,20);
				LET cNombreAcuseN = cPrefijoControl || TRIM(cNombreAcuseN);
				LET cNombreAcuseN = TRIM(cNombreAcuseN);

                LET vsSQLC = '';
				LET vsSQLC = 'rm -f ' || TRIM(sRutaArchivo) ||  trim(cNomArchivo);
				SYSTEM vsSQLC;
                LET vsSQLC = '';
				LET vsSQLC = 'rm -f ' || TRIM(sRutaArchivo) ||  trim(cArchivoControl);
				SYSTEM vsSQLC;
                LET vsSQLC = '';
				LET vsSQLC = 'rm -f ' || TRIM(sRutaArchivo) ||  trim(cNombreAcuseA);
				SYSTEM vsSQLC;
                LET vsSQLC = '';
				LET vsSQLC = 'rm -f ' || TRIM(sRutaArchivo) ||  'load_sat_resp.sql';
				SYSTEM vsSQLC;
				LET vsSQLC = '';
				LET vsSQLC = 'rm -f ' || TRIM(sRutaArchivo) ||  'load_archivo_sat.sql';
				SYSTEM vsSQLC;
				LET vsSQLC = '';
				LET vsSQLC = 'rm -f ' || TRIM(sRutaArchivo) ||  'load_control_resp.sql';
				SYSTEM vsSQLC;
				LET vsSQLC = '';
				LET vsSQLC = 'rm -f ' || TRIM(sRutaArchivo) ||  'load_sat_resp.sql';
				SYSTEM vsSQLC;
				LET vsSQLC = '';
				LET vsSQLC = 'rm -f ' || TRIM(sRutaArchivo) ||  'tmp_SAT_acuse.sql';
				SYSTEM vsSQLC;
                LET vsSQLC = '';
				LET vsSQLC = 'rm -f ' || TRIM(sRutaArchivo) ||  trim(cNombreAcuseN);
				SYSTEM vsSQLC;

                LET cCodRet = '002';
                return cCodRet;
        END IF;
        IF cTipoArchivo = '03' THEN
                LET vsSQLC = '';
				LET vsSQLC = 'rm -f ' || TRIM(sRutaArchivo) ||  'tmp_SAT_acuse.sql';
				SYSTEM vsSQLC;
				LET vsSQLC = '';
				LET vsSQLC = 'rm -f ' || TRIM(sRutaArchivo) ||  trim(cNomArchivo);
				SYSTEM vsSQLC;
                                 LET vsSQLC = '';
				LET vsSQLC = 'rm -f ' || TRIM(sRutaArchivo) ||  trim(cArchivoControl);
				SYSTEM vsSQLC;
                LET cCodRet = '003';
                return cCodRet;
        END IF;
        IF cTipoArchivo = '04' THEN
				LET cPrefijo = '';
                LET cPrefijo = "IA";
				LET cNombreAcuseA = SUBSTR(cNomArchivo,3,20);
				LET cNombreAcuseA = cPrefijo || TRIM(cNombreAcuseA);
				LET cNombreAcuseA = TRIM(cNombreAcuseA);

                LET cPrefijoControl = '';
				LET cPrefijoControl = 'IN';
				LET cNombreAcuseN = SUBSTR(cNomArchivo,3,20);
				LET cNombreAcuseN = cPrefijoControl || TRIM(cNombreAcuseN);
	 			LET cNombreAcuseN = TRIM(cNombreAcuseN);
                LET vsSQLC = '';
				LET vsSQLC = 'rm -f ' || TRIM(sRutaArchivo) ||  trim(cNomArchivo);
				SYSTEM vsSQLC;
                LET vsSQLC = '';
				LET vsSQLC = 'rm -f ' || TRIM(sRutaArchivo) ||  trim(cArchivoControl);
				SYSTEM vsSQLC;
               LET vsSQLC = '';
				LET vsSQLC = 'rm -f ' || TRIM(sRutaArchivo) ||  trim(cNombreAcuseA);
				SYSTEM vsSQLC;
                LET vsSQLC = '';
				LET vsSQLC = 'rm -f ' || TRIM(sRutaArchivo) ||  trim(cNombreAcuseN);
				SYSTEM vsSQLC;
				LET vsSQLC = '';
					LET vsSQLC = 'rm -f ' || TRIM(sRutaArchivo) ||  'load_informe_sat.sql';
					SYSTEM vsSQLC;
					LET vsSQLC = '';
					LET vsSQLC = 'rm -f ' || TRIM(sRutaArchivo) ||  'load_control_sat.sql';
					SYSTEM vsSQLC;
					LET vsSQLC = '';
					LET vsSQLC = 'rm -f ' || TRIM(sRutaArchivo) ||  'tmp_SAT_acuse.sql';
					SYSTEM vsSQLC;
                LET cCodRet = '004';
                return cCodRet;
         END IF;
        IF  cTipoArchivo = '05' THEN
                LET vsSQLC = '';
				LET vsSQLC = 'rm -f ' || TRIM(sRutaArchivo) ||  trim(cNomArchivo);
				SYSTEM vsSQLC;
                LET vsSQLC = '';
					LET vsSQLC = '';
							LET vsSQLC = 'rm -f ' || TRIM(sRutaArchivo) ||  trim(cNomArchivo);
							SYSTEM vsSQLC;
							LET vsSQLC = '';
							LET vsSQLC = 'rm -f ' || TRIM(sRutaArchivo) ||  'load_sat_resp.sql';
							SYSTEM vsSQLC;
							LET vsSQLC = '';
							LET vsSQLC = 'rm -f ' || TRIM(sRutaArchivo) ||  'load_archivo_sat.sql';
							SYSTEM vsSQLC;
							LET vsSQLC = '';
							LET vsSQLC = 'rm -f ' || TRIM(sRutaArchivo) ||  'load_acuse_sat.sql';
							SYSTEM vsSQLC;
                LET cCodRet = '005';
                return cCodRet;
         END IF;
        IF  cTipoArchivo = '06' THEN
                IF EXISTS( SELECT dbsname, tabname FROM sysmaster:systabnames  WHERE tabname = 'sl_acuse') THEN
						DELETE bdilide:sl_acuse;
				ELSE
						CREATE TABLE bdilide:sl_acuse(clave CHAR(5), fecha CHAR(8), registro int, estado int);
				END IF;
                                LET cNombreControl = cNomArchivo;
                                LET cLetraInicial = SUBSTR(cNombreControl,1,1);
                                IF cLetraInicial = 'R' THEN
                                    LET cPrefijoControl = 'RN';
                                END IF;
				   IF cLetraInicial = 'I' THEN
                                    LET cPrefijoControl = 'IN';
                                END IF;
				LET cNombreControl = SUBSTR(cNombreControl,3,20);
				LET cNombreControl = cPrefijoControl || TRIM(cNombreControl);
				LET sBanderaError  = '1';
				LET pMensaje = 'Error en la creacion del archivo   '  ||  TRIM(cNombreControl);
				LET cNombreError = cNombreControl;
				INSERT INTO bdilide:sl_procesos(proceso, fech_proceso,status,user_insert,fecha_insert)
				VALUES(cNombreControl,cFechaSer,'0',pUsuario, current hour to fraction(3));
				INSERT INTO bdilide:sl_acuse(clave,fecha,registro, estado)
				VALUES (cClaveBan, '0', '0','1' );
				LET vsSQL1C = 'echo " SET LOCK MODE TO WAIT; SET ISOLATION TO DIRTY READ; UNLOAD TO ' || TRIM(sRutaArchivo) || TRIM(cNombreControl)  || ' DELIMITER ' || '''|''';
				LET vsSQL2C = ' select clave,fecha,registro,estado from bdilide:sl_acuse;' ;
				LET vsSQL3C = ' " > '|| TRIM(sRutaArchivo) || 'tmp_SAT_acuse.sql;';
				LET vsSQL1C = TRIM(vsSQL1C);
				LET vsSQL3C = TRIM(vsSQL3C);
				LET vsSQLC = TRIM(vsSQL1C) || ' ' ||  TRIM(vsSQL2C) || TRIM(vsSQL3C);
				IF ( vsSQLC <> '' ) THEN
					SYSTEM vsSQLC ;
					let vsSQLC = '' ;
					let vsSQLC = 'dbaccess bdilide ' || TRIM(sRutaArchivo) || 'tmp_SAT_acuse.sql;';
					SYSTEM vsSQLC ;
				END IF;
                LET vsSQLC = '';
                LET vsSQLC  = 'chmod 666 ' || ' ' || TRIM(sRutaArchivo) || TRIM(cNombreControl);
                SYSTEM vsSQLC;
                LET vsSQLC = '';
                LET vsSQLC  = 'chmod 666 ' || ' ' || TRIM(sRutaArchivo) || 'tmp_SAT_acuse.sql;';
                SYSTEM vsSQLC;
				LET sBanderaError  = '2';
				LET pMensaje = 'Error en el envio de AIX hacia Windows del archivo  '  ||  TRIM(cNombreControl);

				INSERT INTO sl_archsat (nombre_arch,fecha_genera,fecha_respuesta,status,no_registros,cod_envio,user_insert,fecha_insert)
				VALUES(cNombreControl, cFechaSer,' ','0','0','0',pUsuario, current hour to fraction(3));
				LET vsSQLC = '';
				LET vsSQLC  = 'scp' || ' ' || TRIM(sRutaArchivo) || TRIM( cNombreControl) || ' ' || TRIM(vIpDest) || TRIM(vUsuarioDestino) || TRIM(cNombreControl);
                                SYSTEM vsSQLC;

				UPDATE sl_archsat SET status = 'E'  WHERE nombre_arch = cNomArchivo;
				--UPDATE sl_archsat SET status = 'E'  WHERE nombre_arch = cArchivoControl;
				LET vsSQLC = '';
				LET vsSQLC = 'rm -f ' || TRIM(sRutaArchivo) ||  'tmp_SAT_acuse.sql;';
				SYSTEM vsSQLC;
				LET vsSQLC = '';
				LET vsSQLC = 'rm -f ' || TRIM(sRutaArchivo) ||  trim(cNomArchivo);
				SYSTEM vsSQLC;
				LET vsSQLC = '';
				LET vsSQLC = 'rm -f ' || TRIM(sRutaArchivo) ||  trim(cArchivoControl);
				SYSTEM vsSQLC;
				LET vsSQLC = '';
				LET vsSQLC = 'rm -f ' || TRIM(sRutaArchivo) ||  trim(cNombreControl);
				SYSTEM vsSQLC;
				LET vsSQLC = 'rm -f ' || TRIM(sRutaArchivo) ||  'load_sat_resp.sql';
				SYSTEM vsSQLC;
				LET vsSQLC = '';
				LET vsSQLC = 'rm -f ' || TRIM(sRutaArchivo) ||  'load_archivo_sat.sql';
				SYSTEM vsSQLC;
				LET vsSQLC = '';
				LET vsSQLC = 'rm -f ' || TRIM(sRutaArchivo) ||  'load_control_resp.sql';
				SYSTEM vsSQLC;
				LET vsSQLC = '';
				LET vsSQLC = 'rm -f ' || TRIM(sRutaArchivo) ||  'load_sat_resp.sql';
				SYSTEM vsSQLC;
        END IF;
    end;
end procedure;