CREATE PROCEDURE "informix".sp_armasentencia_edocob( 
      pfecha_hoy                    DATE
)
returning       CHAR (10);  --50

-- MAHR Agosto 2012. Se parametriza ruta destino: /resplogifx/archivoscartera/

define cSql             CHAR(2500);
define var_rga          CHAR(10);
define cNombreArchivo   CHAR(70);
define vfecha_hoy       DATE;
Define cRutaArch        CHAR(50);

let vfecha_hoy= date(1);
let var_rga = ''; 

--SET DEBUG FILE TO '/informix/sp_armasentencia_edocob.out';
--TRACE ON;

BEGIN
    
    SELECT valor INTO cRutaArch FROM bdinteg:"informix".si_param WHERE cod_param = 137;

            LET  cNombreArchivo = Trim(cRutaArch) || 'EdoCuentaAbogadoBancoppel' || LPAD(TRIM(MONTH(pfecha_hoy)::CHAR(2)),2,'0') || substr(YEAR(pfecha_hoy),3,2) || '.txt';
            let cSql = "";
        --  let cSql = ' UNLOAD TO ' || '''/resplogifx/archivoscartera/CtaAbogadoRegistros.unl''' || ' DELIMITER ' || '''"|"''';   
            let cSql = ' UNLOAD TO ''' || Trim(cRutaArch) || 'CtaAbogadoRegistros.unl''' || ' DELIMITER ' || '''"|"''';
            call bdicred:sp_genera_archivo ('EstadoCtaAbogado.sql',cSql) returning var_rga;
            let cSql =  '  SELECT nvl"("numcte,' || '''" "''' || '")", nvl"("sucursal,' || '''" "''' || '")",';
            call bdicred:sp_genera_archivo ('EstadoCtaAbogado.sql',cSql) returning var_rga;
            let cSql =  '  nvl"("replace"("replace"("nombre1,' || '''"|"''' || '''"|"'''  || ', ' || '''" "''' || '")",' || '''"\"'''  || ',' || '''" "'''  || '")", ' || '''" "'''  || '")", ';
            call bdicred:sp_genera_archivo ('EstadoCtaAbogado.sql',cSql) returning var_rga;
            let cSql =  '  nvl"("replace"("replace"("nombre2,' || '''"|"'''  || ', ' || '''" "''' || '")",' || '''"\"'''  || ',' || '''" "'''  || '")", ' || '''" "'''  || '")", ';
            call bdicred:sp_genera_archivo ('EstadoCtaAbogado.sql',cSql) returning var_rga;
            let cSql =  '  nvl"("replace"("replace"("apellido1,' || '''"|"'''  || ', ' || '''" "''' || '")",' || '''"\"'''  || ',' || '''" "'''  || '")", ' || '''" "'''  || '")", ' ;
	    call bdicred:sp_genera_archivo ('EstadoCtaAbogado.sql',cSql) returning var_rga;
            let cSql =  '  nvl"("replace"("replace"("apellido2,' || '''"|"'''  || ', ' || '''" "''' || '")",' || '''"\"'''  || ',' || '''" "'''  || '")", ' || '''" "'''  || '")", ' ;
            call bdicred:sp_genera_archivo ('EstadoCtaAbogado.sql',cSql) returning var_rga;
            let cSql =  '  nvl"("replace"("replace"("calle,' || '''"|"'''  || ', ' || '''" "''' || '")",' || '''"\"'''  || ',' || '''" "'''  || '")", ' || '''" "'''  || '")", ' ;
            call bdicred:sp_genera_archivo ('EstadoCtaAbogado.sql',cSql) returning var_rga;
            let cSql =  '  nvl"("replace"("replace"("numeroextcalle,' || '''"|"'''  || ', ' || '''" "''' || '")",' || '''"\"'''  || ',' || '''" "'''  || '")", ' || '''" "'''  || '")", ' ;
            call bdicred:sp_genera_archivo ('EstadoCtaAbogado.sql',cSql) returning var_rga;
            let cSql =  '  nvl"("replace"("replace"("numerointcalle,' || '''"|"'''  || ', ' || '''" "''' || '")",' || '''"\"'''  || ',' || '''" "'''  || '")", ' || '''" "'''  || '")", ' ;
            call bdicred:sp_genera_archivo ('EstadoCtaAbogado.sql',cSql) returning var_rga;
            let cSql =  '  nvl"("replace"("replace"("colonia,' || '''"|"'''  || ', ' || '''" "''' || '")",' || '''"\"'''  || ',' || '''" "'''  || '")", ' || '''" "'''  || '")", ' ;
            call bdicred:sp_genera_archivo ('EstadoCtaAbogado.sql',cSql) returning var_rga;
            let cSql =  '  nvl"("replace"("replace"("manzana,' || '''"|"'''  || ', ' || '''" "''' || '")",' || '''"\"'''  || ',' || '''" "'''  || '")", ' || '''" "'''  || '")", ' ;
            call bdicred:sp_genera_archivo ('EstadoCtaAbogado.sql',cSql) returning var_rga;
            let cSql =  '  nvl"("replace"("replace"("otros,' || '''"|"'''  || ', ' || '''" "''' || '")",' || '''"\"'''  || ',' || '''" "'''  || '")", ' || '''" "'''  || '")", ' ;
            call bdicred:sp_genera_archivo ('EstadoCtaAbogado.sql',cSql) returning var_rga;
            let cSql =  '  nvl"("replace"("replace"("andador,' || '''"|"'''  || ', ' || '''" "''' || '")",' || '''"\"'''  || ',' || '''" "'''  || '")", ' || '''" "'''  || '")", ' ;
            call bdicred:sp_genera_archivo ('EstadoCtaAbogado.sql',cSql) returning var_rga;
            let cSql =  '  nvl"("replace"("replace"("etapa,' || '''"|"'''  || ', ' || '''" "''' || '")",' || '''"\"'''  || ',' || '''" "'''  || '")", ' || '''" "'''  || '")", ' ;
            call bdicred:sp_genera_archivo ('EstadoCtaAbogado.sql',cSql) returning var_rga;
            let cSql =  '  nvl"("replace"("replace"("lote,' || '''"|"'''  || ', ' || '''" "''' || '")",' || '''"\"'''  || ',' || '''" "'''  || '")", ' || '''" "'''  || '")", ' ;
	    call bdicred:sp_genera_archivo ('EstadoCtaAbogado.sql',cSql) returning var_rga;
            let cSql =  '  nvl"("replace"("replace"("edificio,' || '''"|"'''  || ', ' || '''" "''' || '")",' || '''"\"'''  || ',' || '''" "'''  || '")", ' || '''" "'''  || '")", ';
            call bdicred:sp_genera_archivo ('EstadoCtaAbogado.sql',cSql) returning var_rga;
            let cSql =  '  nvl"("replace"("replace"("entrada,' || '''"|"'''  || ', ' || '''" "''' || '")",' || '''"\"'''  || ',' || '''" "'''  || '")", ' || '''" "'''  || '")", ' ;
            call bdicred:sp_genera_archivo ('EstadoCtaAbogado.sql',cSql) returning var_rga;
            let cSql =  '  nvl"("replace"("replace"("departamento,' || '''"|"'''  || ', ' || '''" "''' || '")",' || '''"\"'''  || ',' || '''" "'''  || '")", ' || '''" "'''  || '")", ';
            call bdicred:sp_genera_archivo ('EstadoCtaAbogado.sql',cSql) returning var_rga;
            let cSql =  '  nvl"("replace"("replace"("cod_postal,' || '''"|"'''  || ', ' || '''" "''' || '")",' || '''"\"'''  || ',' || '''" "'''  || '")", ' || '''" "'''  || '")", ' ;
            call bdicred:sp_genera_archivo ('EstadoCtaAbogado.sql',cSql) returning var_rga;
            let cSql =  '  nvl"("replace"("replace"("puntocardinal,' || '''"|"'''  || ', ' || '''" "''' || '")",' || '''"\"'''  || ',' || '''" "'''  || '")", ' || '''" "'''  || '")", ';
            call bdicred:sp_genera_archivo ('EstadoCtaAbogado.sql',cSql) returning var_rga;
            let cSql =  '  nvl"("replace"("replace"("complemento,' || '''"|"'''  || ', ' || '''" "''' || '")",' || '''"\"'''  || ',' || '''" "'''  || '")", ' || '''" "'''  || '")", ' ;
            call bdicred:sp_genera_archivo ('EstadoCtaAbogado.sql',cSql) returning var_rga;
            let cSql =  '  nvl"("replace"("replace"("entre_calles,' || '''"|"'''  || ', ' || '''" "''' || '")",' || '''"\"'''  || ',' || '''" "'''  || '")", ' || '''" "'''  || '")", ' ;
            call bdicred:sp_genera_archivo ('EstadoCtaAbogado.sql',cSql) returning var_rga;
            let cSql =  '  nvl"("replace"("replace"("delegacion_municipio,' || '''"|"'''  || ', ' || '''" "''' || '")",' || '''"\"'''  || ',' || '''" "'''  || '")", ' || '''" "'''  || '")", ';
            call bdicred:sp_genera_archivo ('EstadoCtaAbogado.sql',cSql) returning var_rga;
            let cSql =  '  nvl"("replace"("replace"("estado,' || '''"|"'''  || ', ' || '''" "''' || '")",' || '''"\"'''  || ',' || '''" "'''  || '")", ' || '''" "'''  || '")", ';
            call bdicred:sp_genera_archivo ('EstadoCtaAbogado.sql',cSql) returning var_rga;
            let cSql =  '  nvl"("replace"("replace"("telefono_casa,' || '''"|"'''  || ', ' || '''" "''' || '")",' || '''"\"'''  || ',' || '''" "'''  || '")", ' || '''" "'''  || '")", ' ;
            call bdicred:sp_genera_archivo ('EstadoCtaAbogado.sql',cSql) returning var_rga;
            let cSql =  '  nvl"("replace"("replace"("telefono_trabajo,' || '''"|"'''  || ', ' || '''" "''' || '")",' || '''"\"'''  || ',' || '''" "'''  || '")", ' || '''" "'''  || '")", ';
            call bdicred:sp_genera_archivo ('EstadoCtaAbogado.sql',cSql) returning var_rga;
            let cSql =  '  nvl"("replace"("replace"("extension_trabajo,' || '''"|"'''  || ', ' || '''" "''' || '")",' || '''"\"'''  || ',' || '''" "'''  || '")", ' || '''" "'''  || '")", ';
            call bdicred:sp_genera_archivo ('EstadoCtaAbogado.sql',cSql) returning var_rga;
            let cSql =  '  nvl"("replace"("replace"("celular,' || '''"|"'''  || ', ' || '''" "''' || '")",' || '''"\"'''  || ',' || '''" "'''  || '")", ' || '''" "'''  || '")", ';
            call bdicred:sp_genera_archivo ('EstadoCtaAbogado.sql',cSql) returning var_rga;
            let cSql =  '  nvl"("replace"("replace"("lugar_trabajo,' || '''"|"'''  || ', ' || '''" "''' || '")",' || '''"\"'''  || ',' || '''" "'''  || '")", ' || '''" "'''  || '")", ';
            call bdicred:sp_genera_archivo ('EstadoCtaAbogado.sql',cSql) returning var_rga;
            let cSql =  '  nvl"("replace"("replace"("nombrecalletrabajo,' || '''"|"'''  || ', ' || '''" "''' || '")",' || '''"\"'''  || ',' || '''" "'''  || '")", ' || '''" "'''  || '")", ';
            call bdicred:sp_genera_archivo ('EstadoCtaAbogado.sql',cSql) returning var_rga;
            let cSql =  '  nvl"("replace"("replace"("numeroexteriortrabajo,' || '''"|"'''  || ', ' || '''" "''' || '")",' || '''"\"'''  || ',' || '''" "'''  || '")", ' || '''" "'''  || '")", ';
            call bdicred:sp_genera_archivo ('EstadoCtaAbogado.sql',cSql) returning var_rga;
            let cSql =  '  nvl"("replace"("replace"("numerointeriortrabajo,' || '''"|"'''  || ', ' || '''" "''' || '")",' || '''"\"'''  || ',' || '''" "'''  || '")", ' || '''" "'''  || '")", ';
            call bdicred:sp_genera_archivo ('EstadoCtaAbogado.sql',cSql) returning var_rga;
            let cSql =  '  nvl"("replace"("replace"("coloniatrabajo,' || '''"|"'''  || ', ' || '''" "''' || '")",' || '''"\"'''  || ',' || '''" "'''  || '")", ' || '''" "'''  || '")", ';
            call bdicred:sp_genera_archivo ('EstadoCtaAbogado.sql',cSql) returning var_rga;
            let cSql =  '  nvl"("replace"("replace"("manzanatrabajo,' || '''"|"'''  || ', ' || '''" "''' || '")",' || '''"\"'''  || ',' || '''" "'''  || '")", ' || '''" "'''  || '")", ';
            call bdicred:sp_genera_archivo ('EstadoCtaAbogado.sql',cSql) returning var_rga;
            let cSql =  '  nvl"("replace"("replace"("otrostrabajo,' || '''"|"'''  || ', ' || '''" "''' || '")",' || '''"\"'''  || ',' || '''" "'''  || '")", ' || '''" "'''  || '")", ';
            call bdicred:sp_genera_archivo ('EstadoCtaAbogado.sql',cSql) returning var_rga;
            let cSql =  '  nvl"("replace"("replace"("andadortrabajo,' || '''"|"'''  || ', ' || '''" "''' || '")",' || '''"\"'''  || ',' || '''" "'''  || '")", ' || '''" "'''  || '")", ';
            call bdicred:sp_genera_archivo ('EstadoCtaAbogado.sql',cSql) returning var_rga;
            let cSql =  '  nvl"("replace"("replace"("etapatrabajo,' || '''"|"'''  || ', ' || '''" "''' || '")",' || '''"\"'''  || ',' || '''" "'''  || '")", ' || '''" "'''  || '")", ';
            call bdicred:sp_genera_archivo ('EstadoCtaAbogado.sql',cSql) returning var_rga;
            let cSql =  '  nvl"("replace"("replace"("lotetrabajo,' || '''"|"'''  || ', ' || '''" "''' || '")",' || '''"\"'''  || ',' || '''" "'''  || '")", ' || '''" "'''  || '")", ';
            call bdicred:sp_genera_archivo ('EstadoCtaAbogado.sql',cSql) returning var_rga;
            let cSql =  '  nvl"("replace"("replace"("edificiotrabajo,' || '''"|"'''  || ', ' || '''" "''' || '")",' || '''"\"'''  || ',' || '''" "'''  || '")", ' || '''" "'''  || '")", ';
            call bdicred:sp_genera_archivo ('EstadoCtaAbogado.sql',cSql) returning var_rga;
            let cSql =  '  nvl"("replace"("replace"("entradatrabajo,' || '''"|"'''  || ', ' || '''" "''' || '")",' || '''"\"'''  || ',' || '''" "'''  || '")", ' || '''" "'''  || '")", ';
            call bdicred:sp_genera_archivo ('EstadoCtaAbogado.sql',cSql) returning var_rga;
            let cSql =  '  nvl"("replace"("replace"("departamentotrabajo,' || '''"|"'''  || ', ' || '''" "''' || '")",' || '''"\"'''  || ',' || '''" "'''  || '")", ' || '''" "'''  || '")", ';
            call bdicred:sp_genera_archivo ('EstadoCtaAbogado.sql',cSql) returning var_rga;
            let cSql =  '  nvl"("replace"("replace"("codigopostaltrabajo,' || '''"|"'''  || ', ' || '''" "''' || '")",' || '''"\"'''  || ',' || '''" "'''  || '")", ' || '''" "'''  || '")", ';
            call bdicred:sp_genera_archivo ('EstadoCtaAbogado.sql',cSql) returning var_rga;
            let cSql =  '  nvl"("replace"("replace"("puntocardinaltrabajo,' || '''"|"'''  || ', ' || '''" "''' || '")",' || '''"\"'''  || ',' || '''" "'''  || '")", ' || '''" "'''  || '")", ';
            call bdicred:sp_genera_archivo ('EstadoCtaAbogado.sql',cSql) returning var_rga;
            let cSql =  '  nvl"("replace"("replace"("complementotrabajo,' || '''"|"'''  || ', ' || '''" "''' || '")",' || '''"\"'''  || ',' || '''" "'''  || '")", ' || '''" "'''  || '")", ';
            call bdicred:sp_genera_archivo ('EstadoCtaAbogado.sql',cSql) returning var_rga;
            let cSql =  '  nvl"("replace"("replace"("entrecallestrabajo,' || '''"|"'''  || ', ' || '''" "''' || '")",' || '''"\"'''  || ',' || '''" "'''  || '")", ' || '''" "'''  || '")", ';
            call bdicred:sp_genera_archivo ('EstadoCtaAbogado.sql',cSql) returning var_rga;
            let cSql =  '  nvl"("replace"("replace"("delegacion_municipiotrabajo,' || '''"|"'''  || ', ' || '''" "''' || '")",' || '''"\"'''  || ',' || '''" "'''  || '")", ' || '''" "'''  || '")", ';
            call bdicred:sp_genera_archivo ('EstadoCtaAbogado.sql',cSql) returning var_rga;
            let cSql =  '  nvl"("replace"("replace"("estadotrabajo,' || '''"|"'''  || ', ' || '''" "''' || '")",' || '''"\"'''  || ',' || '''" "'''  || '")", ' || '''" "'''  || '")", ';
            call bdicred:sp_genera_archivo ('EstadoCtaAbogado.sql',cSql) returning var_rga;
            let cSql =  '  nvl"("replace"("replace"("numerociudadtrabajo,' || '''"|"'''  || ', ' || '''" "''' || '")",' || '''"\"'''  || ',' || '''" "'''  || '")", ' || '''" "'''  || '")", ';
            call bdicred:sp_genera_archivo ('EstadoCtaAbogado.sql',cSql) returning var_rga;
            let cSql =  '  nvl"("replace"("replace"("numerocoloniatrabajo,' || '''"|"'''  || ', ' || '''" "''' || '")",' || '''"\"'''  || ',' || '''" "'''  || '")", ' || '''" "'''  || '")", ';
            call bdicred:sp_genera_archivo ('EstadoCtaAbogado.sql',cSql) returning var_rga;
            let cSql =  '  nvl"("numero_credito,' || '''" "''' || '")", nvl"("num_tarjeta_credito,' || '''" "''' || '")", ';
            call bdicred:sp_genera_archivo ('EstadoCtaAbogado.sql',cSql) returning var_rga;
            let cSql =  '  nvl"("replace"("replace"("situacioespecial,' || '''"|"'''  || ', ' || '''" "''' || '")",' || '''"\"'''  || ',' || '''" "'''  || '")", ' || '''" "'''  || '")", ' ;
            call bdicred:sp_genera_archivo ('EstadoCtaAbogado.sql',cSql) returning var_rga;
            let cSql =  '  nvl"("replace"("replace"("estado_civil,' || '''"|"'''  || ', ' || '''" "''' || '")",' || '''"\"'''  || ',' || '''" "'''  || '")", ' || '''" "'''  || '")", ' ;
            call bdicred:sp_genera_archivo ('EstadoCtaAbogado.sql',cSql) returning var_rga;
            let cSql =  '  nvl"("replace"("replace"("tipo_casa,' || '''"|"'''  || ', ' || '''" "''' || '")",' || '''"\"'''  || ',' || '''" "'''  || '")", ' || '''" "'''  || '")", ' ;
            call bdicred:sp_genera_archivo ('EstadoCtaAbogado.sql',cSql) returning var_rga;
            let cSql =  '  nvl"("replace"("replace"("sexo,' || '''"|"'''  || ', ' || '''" "''' || '")",' || '''"\"'''  || ',' || '''" "'''  || '")", ' || '''" "'''  || '")", ' ;
            call bdicred:sp_genera_archivo ('EstadoCtaAbogado.sql',cSql) returning var_rga;
            let cSql =  '  nvl"("replace"("replace"("salarios_minimos,' || '''"|"'''  || ', ' || '''" "''' || '")",' || '''"\"'''  || ',' || '''" "'''  || '")", ' || '''" "'''  || '")", ' ;
            call bdicred:sp_genera_archivo ('EstadoCtaAbogado.sql',cSql) returning var_rga;
            let cSql =  '  nvl"("replace"("replace"("anio_alta,' || '''"|"'''  || ', ' || '''" "''' || '")",' || '''"\"'''  || ',' || '''" "'''  || '")", ' || '''" "'''  || '")", ' ;
            call bdicred:sp_genera_archivo ('EstadoCtaAbogado.sql',cSql) returning var_rga;
            let cSql =  '  nvl"("replace"("replace"("anio_nacimiento,' || '''"|"'''  || ', ' || '''" "''' || '")",' || '''"\"'''  || ',' || '''" "'''  || '")", ' || '''" "'''  || '")", ' ;
            call bdicred:sp_genera_archivo ('EstadoCtaAbogado.sql',cSql) returning var_rga;
            let cSql =  '  nvl"("saldo_actual,0")", nvl"("saldo_vencido,0")", nvl"("saldo_moratorio,0")", ' ;
            call bdicred:sp_genera_archivo ('EstadoCtaAbogado.sql',cSql) returning var_rga;
            let cSql =  '  nvl"("pagominimo,0")", nvl"("fecha_ultimoabono,date"("1")"")", ' ;
            call bdicred:sp_genera_archivo ('EstadoCtaAbogado.sql',cSql) returning var_rga;
            let cSql =  '  nvl"("impte_ultimocompromiso,' || '''" "''' || '")", nvl"("fecha_ultimocompac,date"("1")"")", ' ;
            call bdicred:sp_genera_archivo ('EstadoCtaAbogado.sql',cSql) returning var_rga;
            let cSql =  '  nvl"("plazo_compromiso,' || '''" "''' || '")", nvl"("impte_compromisocumplido,' || '''" "''' || '")", ';
            call bdicred:sp_genera_archivo ('EstadoCtaAbogado.sql',cSql) returning var_rga;
            let cSql =  '  nvl"("fecha_cumpliocompromiso,date"("1")"")", nvl"("cumplio_convenio,''"-"''")", ' ;
            call bdicred:sp_genera_archivo ('EstadoCtaAbogado.sql',cSql) returning var_rga;
            let cSql =  '  nvl"("replace"("replace"("num_ciudadcte,' || '''"|"'''  || ', ' || '''" "''' || '")",' || '''"\"'''  || ',' || '''" "'''  || '")", ' || '''" "'''  || '")", ' ;
            call bdicred:sp_genera_archivo ('EstadoCtaAbogado.sql',cSql) returning var_rga;
            let cSql =  '  nvl"("replace"("replace"("num_centro,' || '''"|"'''  || ', ' || '''" "''' || '")",' || '''"\"'''  || ',' || '''" "'''  || '")", ' || '''" "'''  || '")", ' ;
            call bdicred:sp_genera_archivo ('EstadoCtaAbogado.sql',cSql) returning var_rga;
            let cSql =  '  nvl"("replace"("replace"("num_jefe,' || '''"|"'''  || ', ' || '''" "''' || '")",' || '''"\"'''  || ',' || '''" "'''  || '")", ' || '''" "'''  || '")", ' ;
            call bdicred:sp_genera_archivo ('EstadoCtaAbogado.sql',cSql) returning var_rga;
            let cSql =  '  nvl"("replace"("replace"("num_supervisor,' || '''"|"'''  || ', ' || '''" "''' || '")",' || '''"\"'''  || ',' || '''" "'''  || '")", ' || '''" "'''  || '")", ' ;
            call bdicred:sp_genera_archivo ('EstadoCtaAbogado.sql',cSql) returning var_rga;
            let cSql =  '  nvl"("replace"("replace"("num_coloniacte,' || '''"|"'''  || ', ' || '''" "''' || '")",' || '''"\"'''  || ',' || '''" "'''  || '")", ' || '''" "'''  || '")", ' ;
            call bdicred:sp_genera_archivo ('EstadoCtaAbogado.sql',cSql) returning var_rga;
            let cSql =  '  nvl"("replace"("replace"("num_callecte,' || '''"|"'''  || ', ' || '''" "''' || '")",' || '''"\"'''  || ',' || '''" "'''  || '")", ' || '''" "'''  || '")", ' ;
            call bdicred:sp_genera_archivo ('EstadoCtaAbogado.sql',cSql) returning var_rga;
            let cSql =  '  nvl"("replace"("replace"("num_casacte,' || '''"|"'''  || ', ' || '''" "''' || '")",' || '''"\"'''  || ',' || '''" "'''  || '")", ' || '''" "'''  || '")", ' ;
            call bdicred:sp_genera_archivo ('EstadoCtaAbogado.sql',cSql) returning var_rga;
            let cSql =  '  nvl"("pago_vencido,0")", nvl"("fecha_diaultimopago,' || '''" "''' || '")", nvl"("fecha_mesultimopago,' || '''" "''' || '")", ' ;
            call bdicred:sp_genera_archivo ('EstadoCtaAbogado.sql',cSql) returning var_rga;
            let cSql =  '  nvl"("fecha_anioultimopago,' || '''" "''' || '")", nvl"("fecha_diaultimoacuerdo,' || '''" "''' || '")", ' ;
            call bdicred:sp_genera_archivo ('EstadoCtaAbogado.sql',cSql) returning var_rga;
            let cSql =  '  nvl"("fecha_mesultimoacuerdo,' || '''" "''' || '")", nvl"("fecha_anioultimoacuerdo,' || '''" "''' || '")", ' ;
            call bdicred:sp_genera_archivo ('EstadoCtaAbogado.sql',cSql) returning var_rga;
            let cSql =  '  nvl"("tipodecliente,' || '''" "''' || '")", nvl"("causasituacionespecial,' || '''" "''' || '")", ' ;
            call bdicred:sp_genera_archivo ('EstadoCtaAbogado.sql',cSql) returning var_rga;
            let cSql =  '  nvl"("abonos_vdos,0")", nvl"("num_avisos,0")", ' ;
            call bdicred:sp_genera_archivo ('EstadoCtaAbogado.sql',cSql) returning var_rga;
            let cSql =  '  nvl"("replace"("replace"("nom_ref,' || '''"|"'''  || ', ' || '''" "''' || '")",' || '''"\"'''  || ',' || '''" "'''  || '")", ' || '''" "'''  || '")", ' ;
            call bdicred:sp_genera_archivo ('EstadoCtaAbogado.sql',cSql) returning var_rga;
            let cSql =  '  nvl"("replace"("replace"("nom_calle_ref,' || '''"|"'''  || ', ' || '''" "''' || '")",' || '''"\"'''  || ',' || '''" "'''  || '")", ' || '''" "'''  || '")", ' ;
            call bdicred:sp_genera_archivo ('EstadoCtaAbogado.sql',cSql) returning var_rga;
            let cSql =  '  nvl"("replace"("replace"("num_ext_ref,' || '''"|"'''  || ', ' || '''" "''' || '")",' || '''"\"'''  || ',' || '''" "'''  || '")", ' || '''" "'''  || '")", ' ;
            call bdicred:sp_genera_archivo ('EstadoCtaAbogado.sql',cSql) returning var_rga;
            let cSql =  '  nvl"("replace"("replace"("num_int_ref,' || '''"|"'''  || ', ' || '''" "''' || '")",' || '''"\"'''  || ',' || '''" "'''  || '")", ' || '''" "'''  || '")", ' ;
            call bdicred:sp_genera_archivo ('EstadoCtaAbogado.sql',cSql) returning var_rga;
            let cSql =  '  nvl"("replace"("replace"("col_ref,' || '''"|"'''  || ', ' || '''" "''' || '")",' || '''"\"'''  || ',' || '''" "'''  || '")", ' || '''" "'''  || '")", ' ;
            call bdicred:sp_genera_archivo ('EstadoCtaAbogado.sql',cSql) returning var_rga;
            let cSql =  '  nvl"("replace"("replace"("manzana_ref,' || '''"|"'''  || ', ' || '''" "''' || '")",' || '''"\"'''  || ',' || '''" "'''  || '")", ' || '''" "'''  || '")", ' ;
            call bdicred:sp_genera_archivo ('EstadoCtaAbogado.sql',cSql) returning var_rga;
            let cSql =  '  nvl"("replace"("replace"("otros_ref,' || '''"|"'''  || ', ' || '''" "''' || '")",' || '''"\"'''  || ',' || '''" "'''  || '")", ' || '''" "'''  || '")", ' ;
            call bdicred:sp_genera_archivo ('EstadoCtaAbogado.sql',cSql) returning var_rga;
            let cSql =  '  nvl"("replace"("replace"("andador_ref,' || '''"|"'''  || ', ' || '''" "''' || '")",' || '''"\"'''  || ',' || '''" "'''  || '")", ' || '''" "'''  || '")", ' ;
            call bdicred:sp_genera_archivo ('EstadoCtaAbogado.sql',cSql) returning var_rga;
            let cSql =  '  nvl"("replace"("replace"("etapa_ref,' || '''"|"'''  || ', ' || '''" "''' || '")",' || '''"\"'''  || ',' || '''" "'''  || '")", ' || '''" "'''  || '")", ' ;
            call bdicred:sp_genera_archivo ('EstadoCtaAbogado.sql',cSql) returning var_rga;
            let cSql =  '  nvl"("replace"("replace"("lote_ref,' || '''"|"'''  || ', ' || '''" "''' || '")",' || '''"\"'''  || ',' || '''" "'''  || '")", ' || '''" "'''  || '")", ' ;
            call bdicred:sp_genera_archivo ('EstadoCtaAbogado.sql',cSql) returning var_rga;
            let cSql =  '  nvl"("replace"("replace"("edificio_ref,' || '''"|"'''  || ', ' || '''" "''' || '")",' || '''"\"'''  || ',' || '''" "'''  || '")", ' || '''" "'''  || '")", ' ;
            call bdicred:sp_genera_archivo ('EstadoCtaAbogado.sql',cSql) returning var_rga;
            let cSql =  '  nvl"("replace"("replace"("entrada_ref,' || '''"|"'''  || ', ' || '''" "''' || '")",' || '''"\"'''  || ',' || '''" "'''  || '")", ' || '''" "'''  || '")", ' ;
            call bdicred:sp_genera_archivo ('EstadoCtaAbogado.sql',cSql) returning var_rga;
            let cSql =  '  nvl"("replace"("replace"("depto_ref,' || '''"|"'''  || ', ' || '''" "''' || '")",' || '''"\"'''  || ',' || '''" "'''  || '")", ' || '''" "'''  || '")", ' ;
	    call bdicred:sp_genera_archivo ('EstadoCtaAbogado.sql',cSql) returning var_rga;
            let cSql =  '  nvl"("replace"("replace"("cp_ref,' || '''"|"'''  || ', ' || '''" "''' || '")",' || '''"\"'''  || ',' || '''" "'''  || '")", ' || '''" "'''  || '")", ' ;
            call bdicred:sp_genera_archivo ('EstadoCtaAbogado.sql',cSql) returning var_rga;
            let cSql =  '  nvl"("replace"("replace"("punto_cardinal_ref,' || '''"|"'''  || ', ' || '''" "''' || '")",' || '''"\"'''  || ',' || '''" "'''  || '")", ' || '''" "'''  || '")", ' ;
            call bdicred:sp_genera_archivo ('EstadoCtaAbogado.sql',cSql) returning var_rga;
            let cSql =  '  nvl"("replace"("replace"("complemento_ref,' || '''"|"'''  || ', ' || '''" "''' || '")",' || '''"\"'''  || ',' || '''" "'''  || '")", ' || '''" "'''  || '")", ' ;
            call bdicred:sp_genera_archivo ('EstadoCtaAbogado.sql',cSql) returning var_rga;
            let cSql =  '  nvl"("replace"("replace"("entre_calles_ref,' || '''"|"'''  || ', ' || '''" "''' || '")",' || '''"\"'''  || ',' || '''" "'''  || '")", ' || '''" "'''  || '")", ' ;
            call bdicred:sp_genera_archivo ('EstadoCtaAbogado.sql',cSql) returning var_rga;
            let cSql =  '  nvl"("replace"("replace"("delegacion_municipio_ref,' || '''"|"'''  || ', ' || '''" "''' || '")",' || '''"\"'''  || ',' || '''" "'''  || '")", ' || '''" "'''  || '")", ' ;
            call bdicred:sp_genera_archivo ('EstadoCtaAbogado.sql',cSql) returning var_rga;
            let cSql =  '  nvl"("replace"("replace"("estado_ref,' || '''"|"'''  || ', ' || '''" "''' || '")",' || '''"\"'''  || ',' || '''" "'''  || '")", ' || '''" "'''  || '")", ' ;
            call bdicred:sp_genera_archivo ('EstadoCtaAbogado.sql',cSql) returning var_rga;
            let cSql =  '  nvl"("replace"("replace"("telefono_ref,' || '''"|"'''  || ', ' || '''" "''' || '")",' || '''"\"'''  || ',' || '''" "'''  || '")", ' || '''" "'''  || '")", ' ;
            call bdicred:sp_genera_archivo ('EstadoCtaAbogado.sql',cSql) returning var_rga;
            let cSql =  '  nvl"("replace"("replace"("num_ciudad_ref,' || '''"|"'''  || ', ' || '''" "''' || '")",' || '''"\"'''  || ',' || '''" "'''  || '")", ' || '''" "'''  || '")", ' ;
            call bdicred:sp_genera_archivo ('EstadoCtaAbogado.sql',cSql) returning var_rga;
            let cSql =  '  nvl"("replace"("replace"("num_coloniaref,' || '''"|"'''  || ', ' || '''" "''' || '")",' || '''"\"'''  || ',' || '''" "'''  || '")", ' || '''" "'''  || '")", ' ;
            call bdicred:sp_genera_archivo ('EstadoCtaAbogado.sql',cSql) returning var_rga;
            let cSql =  '  nvl"("replace"("replace"("nom_conyugeofamiliar,' || '''"|"'''  || ', ' || '''" "''' || '")",' || '''"\"'''  || ',' || '''" "'''  || '")", ' || '''" "'''  || '")", ' ;
            call bdicred:sp_genera_archivo ('EstadoCtaAbogado.sql',cSql) returning var_rga;
            let cSql =  '  nvl"("replace"("replace"("tel_conyugeofamiliar,' || '''"|"'''  || ', ' || '''" "''' || '")",' || '''"\"'''  || ',' || '''" "'''  || '")", ' || '''" "'''  || '")", ' ;
            call bdicred:sp_genera_archivo ('EstadoCtaAbogado.sql',cSql) returning var_rga;
            let cSql =  '  nvl"("saldovencido1,0")", nvl"("saldovencido2,0")", nvl"("saldovencido3,0")", nvl"("saldovencido4,0")", nvl"("saldovencido5,0")", nvl"("saldovencido6,0")", ' ;
            call bdicred:sp_genera_archivo ('EstadoCtaAbogado.sql',cSql) returning var_rga;
	          let cSql =  '  nvl"("interesmoratorio1,0")", nvl"("interesmoratorio2,0")", nvl"("interesmoratorio3,0")",nvl"("interesmoratorio4,0")", nvl"("interesmoratorio5,0")", ' ;
            call bdicred:sp_genera_archivo ('EstadoCtaAbogado.sql',cSql) returning var_rga;
            --let cSql =  ' nvl"("interesmoratorio6,0")", nvl"("num_producto,0")", nvl"("num_cta,0")", nvl"("imp_ult_abono,0")" ,nvl"("rfc,'|| '''" "''' || '")" ';
            let cSql =  ' nvl"("interesmoratorio6,0")", nvl"("num_producto,0")", nvl"("num_cta,0")", nvl"("imp_ult_abono,0")" ,nvl"("rfc,'|| '''" "''' || '")", ';
	          call bdicred:sp_genera_archivo ('EstadoCtaAbogado.sql',cSql) returning var_rga;
            let cSql =  '  nvl"("replace"("replace"("tipo_dir,' || '''"|"'''  || ', ' || '''" "''' || '")",' || '''"\"'''  || ',' || '''" "'''  || '")", ' || '''" "'''  || '")," ' ;
            call bdicred:sp_genera_archivo ('EstadoCtaAbogado.sql',cSql) returning var_rga;	    
            let cSql =  '  nvl"("replace"("replace"("numcte_ref,' || '''"|"'''  || ', ' || '''" "''' || '")",' || '''"\"'''  || ',' || '''" "'''  || '")", ' || '''" "'''  || '")," ' ;
            call bdicred:sp_genera_archivo ('EstadoCtaAbogado.sql',cSql) returning var_rga;
            --let cSql =  '  nvl"("replace"("replace"("tipovencido,' || '''"|"'''  || ', ' || '''" "''' || '")",' || '''"\"'''  || ',' || '''" "'''  || '")", ' || '''" "'''  || '")" ' ;
            let cSql =  '  nvl"("tipovencido,0")" ';
            call bdicred:sp_genera_archivo ('EstadoCtaAbogado.sql',cSql) returning var_rga;
            let cSql =  '  FROM bdinteg:si_cteestadocuenta c WHERE year"("fecha_movto")" = ' || year(pfecha_hoy) ;
            call bdicred:sp_genera_archivo ('EstadoCtaAbogado.sql',cSql) returning var_rga;
            let cSql =  '  and month"("fecha_movto")" = ' || month(pfecha_hoy) ;
            call bdicred:sp_genera_archivo ('EstadoCtaAbogado.sql',cSql) returning var_rga;
            let cSql =  '  and day"("fecha_movto")" = ' || day(pfecha_hoy) || '";"';
            call bdicred:sp_genera_archivo ('EstadoCtaAbogado.sql',cSql) returning var_rga;

            LET cSql = '';
                --LET cSql = 'dbaccess bdinteg /informix/EstadoCtaAbogado.sql';   --este comment ya estaba
			LET cSql = 'dbaccess bdinteg EstadoCtaAbogado.sql';   
                --LET cSql = 'dbaccess bdinteg /resplogifx/archivoscartera/EstadoCtaAbogado.sql';   --- Prueba
			SYSTEM cSql; 
                --LET cSql = "sed 's/|$//g' /resplogifx/archivoscartera/CtaAbogadoRegistros.unl > /resplogifx/archivoscartera/paso001.txt ";   
            LET cSql = "sed 's/|$//g' " || trim(cRutaArch) || "CtaAbogadoRegistros.unl > " || trim(cRutaArch) || "paso001.txt ";   
            SYSTEM cSql;  LET cSql = '';             
                --LET cSql = "sed 's/" || '"' ||  "//g' /resplogifx/archivoscartera/paso001.txt > " || cNombreArchivo;
            --LET cSql = "sed 's/" || '"' ||  "//g' " || trim(cRutaArch) || "paso001.txt > " || cNombreArchivo;
            LET cSql = "sed 's/" || '"' ||  "//g' " || trim(cRutaArch) || "paso001.txt > " || trim(cRutaArch) || "EdoCobranzaTemp" ||month(pfecha_hoy)||year(pfecha_hoy)||".txt ";
            SYSTEM cSql;  LET cSql = '';

            LET cSql = "cp " || trim(cRutaArch) || "EdoCobranzaTemp" ||month(pfecha_hoy)||year(pfecha_hoy)||".txt " ||  cNombreArchivo;
            SYSTEM cSql;  LET cSql = '';

            LET cSql = "rm " || trim(cRutaArch) || "EdoCobranzaTemp" ||month(pfecha_hoy)||year(pfecha_hoy)||".txt ";
            SYSTEM cSql;  LET cSql = '';

        return var_rga;
        
END;
END PROCEDURE;