CREATE PROCEDURE "informix".sp_actualiza_bitacora_ine()
RETURNING CHAR(5)  AS cCodRet;

--Definicion de Variables
DEFINE cCodRet			CHAR(5);
DEFINE iSqlErr 			INTEGER;
DEFINE sNumCte			CHAR(20);
DEFINE dFechaIFE		DATETIME YEAR to FRACTION(3);
DEFINE iContador 	    INTEGER;

DEFINE sPonderacion    SMALLINT;
DEFINE cSituacionCte   CHAR(1);
DEFINE sCausaCte       SMALLINT;

--Inicializacion de Variables
LET cCodRet    		= '00000';
LET iSqlErr 		= 0;
LET sNumCte 		= "";
LET iContador       = 0;

LET sPonderacion = "0";
LET cSituacionCte   ="";
LET sCausaCte  = 0;

BEGIN

	ON EXCEPTION
		SET iSqlErr
		IF iSqlErr <> 0 THEN
			LET cCodRet = iSqlErr;
			ROLLBACK WORK;
			RETURN cCodRet;
		END IF;
	END EXCEPTION;

	SET LOCK MODE TO WAIT 3;
	SET ISOLATION TO DIRTY READ;

	DROP TABLE IF EXISTS TMPSI_BITACORA_IFE20181103;
	DROP TABLE IF EXISTS TMPSI_BITACORA_IFE20181118;

	SELECT NUMCTE, MAX( FECHA ) AS FECHA
	FROM SI_BITACORA_IFE
	WHERE FECHA BETWEEN EXTEND(MDY(11,03,2018), YEAR to SECOND)+00 UNITS HOUR+00 UNITS MINUTE+00 UNITS SECOND
	AND EXTEND(MDY(11,03,2018), YEAR to SECOND)+23 UNITS HOUR+59 UNITS MINUTE+59 UNITS SECOND
	AND flag_ws = 1
	AND cod_resp_ife = ''
	AND ( ( CASE WHEN test_uv_reflec_anv = 'FAIL' THEN 0 ELSE 1 END )+
		( CASE WHEN test_uv_shape_anv = 'FAIL' THEN 0 ELSE 1 END )+
		( CASE WHEN test_ir_ink_anv = 'FAIL' THEN 0 ELSE 1 END )+
		( CASE WHEN test_uv_reflectance_rev = 'FAIL' THEN 0 ELSE 1 END )+
		( CASE WHEN test_ir_ink_rev = 'FAIL' THEN 0 ELSE 1 END ) ) >= 3
	AND NUMCTE IN
	( SELECT NUMCTE FROM BDISITESP:SE_CTESSITESPCTE WHERE situacion||causa = 'P109' )
	GROUP BY NUMCTE
	INTO TEMP TMPSI_BITACORA_IFE20181103;

	SELECT NUMCTE, MAX( FECHA ) AS FECHA
	FROM SI_BITACORA_IFE
	WHERE FECHA BETWEEN EXTEND(MDY(11,18,2018), YEAR to SECOND)+00 UNITS HOUR+00 UNITS MINUTE+00 UNITS SECOND
	AND EXTEND(MDY(11,18,2018), YEAR to SECOND)+23 UNITS HOUR+59 UNITS MINUTE+59 UNITS SECOND
	AND flag_ws = 1
	AND cod_resp_ife = ''
	AND ( ( CASE WHEN test_uv_reflec_anv = 'FAIL' THEN 0 ELSE 1 END )+
		( CASE WHEN test_uv_shape_anv = 'FAIL' THEN 0 ELSE 1 END )+
		( CASE WHEN test_ir_ink_anv = 'FAIL' THEN 0 ELSE 1 END )+
		( CASE WHEN test_uv_reflectance_rev = 'FAIL' THEN 0 ELSE 1 END )+
		( CASE WHEN test_ir_ink_rev = 'FAIL' THEN 0 ELSE 1 END ) ) >= 3
	AND NUMCTE IN
	( SELECT NUMCTE FROM BDISITESP:SE_CTESSITESPCTE WHERE situacion||causa = 'P109' )
	GROUP BY NUMCTE
	INTO TEMP TMPSI_BITACORA_IFE20181118;

	CREATE INDEX "informix".idx_TMPSI_BITACORA_IFE20181103_cte ON TMPSI_BITACORA_IFE20181103(numcte);
	CREATE INDEX "informix".idx_TMPSI_BITACORA_IFE20181118_cte ON TMPSI_BITACORA_IFE20181118(numcte);

	DELETE FROM TMPSI_BITACORA_IFE20181103 WHERE NUMCTE IN
	(   SELECT NUMCTE
		FROM SI_BITACORA_IFE
		WHERE FECHA BETWEEN EXTEND(MDY(11,04,2018), YEAR to SECOND)+00 UNITS HOUR+00 UNITS MINUTE+00 UNITS SECOND
						AND EXTEND(MDY(11,29,2018), YEAR to SECOND)+23 UNITS HOUR+59 UNITS MINUTE+59 UNITS SECOND
		--AND flag_ws = 1
		--AND cod_resp_ife = ''
		AND resultado = 'Falso'
	);

	DELETE FROM TMPSI_BITACORA_IFE20181118 WHERE NUMCTE IN
	(   SELECT NUMCTE
		FROM SI_BITACORA_IFE
		WHERE FECHA BETWEEN EXTEND(MDY(11,19,2018), YEAR to SECOND)+00 UNITS HOUR+00 UNITS MINUTE+00 UNITS SECOND
						AND EXTEND(MDY(11,29,2018), YEAR to SECOND)+23 UNITS HOUR+59 UNITS MINUTE+59 UNITS SECOND
		--AND flag_ws = 1
		--AND cod_resp_ife = ''
		AND resultado = 'Falso'
	);

	INSERT INTO TMPSI_BITACORA_IFE20181118 ( NUMCTE, fecha )
	SELECT NUMCTE, fecha FROM TMPSI_BITACORA_IFE20181103;

     --SET DEBUG FILE TO "/tmp/ivan/sp_actualiza_bitacora_ine.out";
	 --TRACE ON;
	 
	BEGIN WORK;

    FOREACH WITH HOLD SELECT numcte, fecha INTO sNumCte, dFechaIFE FROM TMPSI_BITACORA_IFE20181118
	
		LET sNumCte = TRIM( sNumCte );
	
	    LET iContador = iContador + 1;
		
		UPDATE bdinteg:si_bitacora_ife
		SET resultado = 'Verdadero', causa_rechazo = 'Datos Validos de acuerdo al WS del IFE'
		WHERE numcte = sNumCte AND fecha = dFechaIFE;
		
		EXECUTE PROCEDURE bdisitesp:"informix".sp_insertasitesp(5,'001',sNumCte,'P',109,'', '','', '', '','','')
		INTO cCodRet, sPonderacion,cSituacionCte,sCausaCte;

        IF( iContador = 1000 ) THEN
            COMMIT WORK;
            LET iContador = 0;
			BEGIN WORK;
        END IF;
        
    END FOREACH;

    COMMIT WORK;
	
	DROP TABLE IF EXISTS TMPSI_BITACORA_IFE20181103;
	DROP TABLE IF EXISTS TMPSI_BITACORA_IFE20181118;	

	RETURN cCodRet;

END;

END PROCEDURE;