CREATE PROCEDURE "informix".sp_actualizapaws_bpi(pEmpresa char(3), pNumCte char(20), pPass char(50), pIp char (15), pSucVirtual char (4), pUsuVirtual char(8))                                                                                
   returning char(5);                                                                                                                                                                                                                         
                                                                                                                                                                                                                                              
                                                                                                                                                                                                                                              
   --Modificó: Javier A. Chávez T.                                                                                                                                                                                                            
   --Actividad: activa el usuario y registra el cambio de status                                                                                                                                                                              
   --Solicito: Mauricio León                                                                                                                                                                                                                  
   --Fecha: 05-03-09  

  --Se crea spl con el nombre modificado
  --RQI CheckmarxB18  BPI
  --Gabrieal Aguilar  
  --10-03-2025  
                                                                                                                                                                                                                                              
                                                                                                                                                                                                                                              
-- ***************************************************************************                                                                                                                                                                
-- Define variables                                                                                                                                                                                                                           
-- ***************************************************************************                                                                                                                                                                
    DEFINE cod_ret char(5);                                                                                                                                                                                                                   
    DEFINE sql_err integer ;                                                                                                                                                                                                                  
    DEFINE iStatus smallint ;                                                                                                                                                                                                                 
    --DEFINE iStBloqueado smallint ;                                                                                                                                                                                                          
   -- DEFINE iStActivado smallint ;                                                                                                                                                                                                           
                                                                                                                                                                                                                                              
-- ***************************************************************************                                                                                                                                                                
-- Inicializa variables                                                                                                                                                                                                                       
-- ***************************************************************************                                                                                                                                                                
   LET cod_ret  = "000";                                                                                                                                                                                                                      
   LET iStatus = 0;                                                                                                                                                                                                                           
   --LET iStBloqueado = 0;                                                                                                                                                                                                                    
   --LET iStActivado = 0;                                                                                                                                                                                                                                                                                                                                                                                                                                                               
      
--SET DEBUG FILE TO "/home/informix/ivonne/sp_actualizapaws_bpi.out";
--TRACE ON;
                                                                                                                                                                                                                                             
BEGIN                                                                                                                                                                                                                                         
                                                                                                                                                                                                                                              
   ON EXCEPTION SET sql_err                                                                                                                                                                                                                   
      IF sql_err <> 0 THEN                                                                                                                                                                                                                    
            let cod_ret = sql_err;                                                                                                                                                                                                            
            RETURN cod_ret;                                                                                                                                                                                                                   
      END IF ;                                                                                                                                                                                                                                
   END EXCEPTION ;                                                                                                                                                                                                                            
                                                                                                                                                                                                                                              
                                                                                                                                                                                                                                              
   IF EXISTS ( SELECT numcte FROM bdinteg:si_bpiusuarios WHERE empresa = pEmpresa AND numcte = pNumCte ) THEN                                                                                                                                 
                                                                                                                                                                                                                                              
        UPDATE bdinteg:si_bpiusuarios SET pass3 = pass2, pass2 = pass1, pass1 = pass, f_pass3 = f_pass2,                                                                                                                                      
                        f_pass2 = f_pass1, f_pass1 = f_pass, pass = pPass, f_pass = current, f_actualizacion = current                                                                                                                        
                         WHERE  empresa = pEmpresa AND numcte = pNumCte;                                                                                                                                                                      
                                                                                                                                                                                                                                              
        SELECT id_status INTO iStatus FROM bdinteg:si_bpiusuarios  WHERE empresa = pEmpresa AND numcte = pNumCte;                                                                                                                             
        --SELECT id_status INTO iStBloqueado FROM bdinteg:si_catstatus  WHERE desc_status = 'BLOQUEADO';                                                                                                                                      
        --SELECT id_status INTO iStActivado FROM bdinteg:si_catstatus  WHERE desc_status = 'ACTIVADO';                                                                                                                                        
                                                                                                                                                                                                                                              
        --IF iStatus = iStBloqueado THEN                                                                                                                                                                                                      
                                                                                                                                                                                                                                              
			IF iStatus = 40 OR  iStatus = 90 THEN                                                                                                                                                                                 
				INSERT INTO bdinteg:si_cambiostcte  (numcliente, id_statusanterior, id_statusactual, ipusuario, fecha_cambio, suc_cambio, usuario_cambio)  VALUES (pNumCte,iStatus,30,pIp ,current, pSucVirtual, pUsuVirtual);
				--UPDATE bdinteg:si_bpiusuarios SET id_status = iStActivado, f_status = current WHERE empresa = pEmpresa AND numcte = pNumCte;                                                                                
				UPDATE bdinteg:si_bpiusuarios SET id_status = 30, f_status = current WHERE empresa = pEmpresa AND numcte = pNumCte;                                                                                           
                                                                                                                                                                                                                                              
			END IF ;                                                                                                                                                                                                              
                        --Se modifica el insert, para que al grabar en tabla la hora tenga un segundo mas, evitando el problema de cambio de servicio básico a avanzado                                                                                                                                                                                                               
			INSERT INTO bdinteg:si_cambiostcte (numcliente, id_statusanterior, id_statusactual, ipusuario, fecha_cambio, suc_cambio, usuario_cambio) VALUES (pNumCte,35,iStatus,pIp,current + 1 units second,pSucVirtual,pUsuVirtual);             
                                                                                                                                                                                                                                              
                                                                                                                                                                                                                                              
                                                                                                                                                                                                                                              
   ELSE                                                                                                                                                                                                                                       
                                                                                                                                                                                                                                              
        LET cod_ret = '001';  -- No existe el Cliente                                                                                                                                                                                         
                                                                                                                                                                                                                                              
   END IF ;                                                                                                                                                                                                                                   
                                                                                                                                                                                                                                              
   RETURN cod_ret;                                                                                                                                                                                                                            
                                                                                                                                                                                                                                              
END                                                                                                                                                                                                                                           
                                                                                                                                                                                                                                              
END PROCEDURE ;