CREATE PROCEDURE "informix".sp_actualiza_acum_ini_periodo(P_EMPRESA		VARCHAR(3),
      P_NUM_CREDITO	VARCHAR(20),
      P_FECHA_CUOTA     DATE
     ) RETURNING VARCHAR(5), VARCHAR(80);

DEFINE  P_COD_RET      VARCHAR(5);
DEFINE  P_MENSAJE      VARCHAR(80);
DEFINE  V_MONTO_CUOTA  DECIMAL(18,2);

DEFINE  SQL_ERR          INTEGER;
DEFINE  ISAM_ERR         INTEGER;
DEFINE  ERROR_INFO       VARCHAR(80);

BEGIN
   ON EXCEPTION SET SQL_ERR, ISAM_ERR, ERROR_INFO
      LET P_COD_RET    = SQL_ERR;
      LET P_MENSAJE  = ERROR_INFO;
      RETURN P_COD_RET, P_MENSAJE;
   END EXCEPTION;

   LET P_COD_RET = '00000';
   LET P_MENSAJE = 'PROCESO EXITOSO';

   SELECT MONTO_CUOTA
   INTO   V_MONTO_CUOTA
   FROM   SD_PAGINTER
   WHERE  EMPRESA     = P_EMPRESA
   AND    NUM_CREDITO = P_NUM_CREDITO
   AND    FECHA_CUOTA = P_FECHA_CUOTA;

   UPDATE SD_MAESDOS
   SET SDO_NO_EXIG      = SDO_NO_EXIG + V_MONTO_CUOTA,
       SDO_ACUM_INTPER  = 0,
       DIAS_ACUM_INTPER = 0
   WHERE  NUM_CREDITO = P_NUM_CREDITO
   AND    EMPRESA	 = P_EMPRESA;

   RETURN P_COD_RET, P_MENSAJE;
END;
END PROCEDURE;