CREATE PROCEDURE "informix".revsol( P_EMPRESA  VARCHAR(3)
                        , P_CREDITO  VARCHAR(20)
                        )
RETURNING VARCHAR(10), VARCHAR(80);
--, P_ERROR     OUT VARCHAR2
--, P_MENSAJE   OUT VARCHAR2

DEFINE P_ERROR    VARCHAR(10);
DEFINE P_MENSAJE  VARCHAR(80);
DEFINE SQL_ERR    INTEGER;
DEFINE ISAM_ERR   INTEGER;
DEFINE ERROR_INFO VARCHAR(200);

BEGIN
   ON EXCEPTION SET SQL_ERR, ISAM_ERR, ERROR_INFO
      LET P_ERROR   = SQL_ERR;
      LET P_MENSAJE = ERROR_INFO;
      RETURN P_ERROR, P_MENSAJE;
   END EXCEPTION;

   LET P_ERROR   = '00000';
   LET P_MENSAJE = 'PROCESO EXITOSO';

   --SE BORRAN LO REGISTROS CREADOS PARA SD_PAGOCAPIT
   DELETE FROM SD_PAGOCAPIT
   WHERE  NUM_CREDITO = P_CREDITO
   AND    EMPRESA     = P_EMPRESA;

   --SE BORRAN LO REGISTROS CREADOS PARA SS_PAGINTER
   DELETE FROM SD_PAGINTER
   WHERE  NUM_CREDITO = P_CREDITO
   AND    EMPRESA     = P_EMPRESA;

   --ACTUALIZA EL STATUS DE LA SOLICITUD
   UPDATE BDISOLIC:SS_SOLICITUDES
   SET    STATUS_SOLICITUD = 'AC'
   WHERE  NUM_SOLICITUD = P_CREDITO
   AND    EMPRESA =  P_EMPRESA;

   --ACTUALIZA EL STATUS DEL CONTRATO 
   UPDATE BDISOLIC:SS_MAECONTRATO
   SET    ESTADO_CONTRATO = 'A'
   WHERE  NUM_CONTRATO = P_CREDITO
   AND    EMPRESA =  P_EMPRESA;

   RETURN P_ERROR, P_MENSAJE;

END;
END PROCEDURE;