CREATE PROCEDURE "informix".reversa_mov_dia( P_EMPRESA       VARCHAR(3)
                         , P_NUM_CREDITO   VARCHAR(20)
		         , P_FOLIO_SUC  VARCHAR(16)
                         )
RETURNING VARCHAR(8), VARCHAR(80);

DEFINE  P_COD_RET VARCHAR(8);
DEFINE  P_MENSAJE VARCHAR(80);

DEFINE  V_NUM_PRODUCTO  LIKE SD_MAECRED.NUM_PRODUCTO;
DEFINE  V_CODIGO_REF    LIKE SD_TRANSFUN.CODIGO_REF;
DEFINE  V_CODIGO_FUN    LIKE SD_TRANSFUN.CODIGO_FUN;
DEFINE  V_FECHA_HOY     DATE;
DEFINE  V_MONTO         INTEGER;
DEFINE  V_FOLIO_SUC     VARCHAR(16);
DEFINE  V_SUCURSAL      LIKE SD_MAECRED.SUCURSAL;
DEFINE  V_DIVISA        LIKE SD_MAECRED.DIVISA;
DEFINE  V_TRANSACC_SUC  VARCHAR(4);

BEGIN
   LET V_TRANSACC_SUC = '0000';
   LET P_COD_RET  = '00000';
   LET P_MENSAJE = 'PROCESO EXITOSO';

   --SELECCIONA LA FECHA DE HOY
   SELECT FECHA_HOY
   INTO   V_FECHA_HOY
   FROM   SD_FECHAS
   WHERE  EMPRESA = P_EMPRESA;

   --SELECCIONA EL NUMERO DE PRODUCTO, EL FOLIO_SUC, LA SUCURSAL, LA DIVISA
{   SELECT NUM_PRODUCTO, SUBSTR(USER,1,8) || current hour to fraction (3) FOLIO_SUC, SUCURSAL, DIVISA
   INTO   V_NUM_PRODUCTO, V_FOLIO_SUC, V_SUCURSAL, V_DIVISA
   FROM   SD_MAECRED
   WHERE  EMPRESA     = P_EMPRESA
   AND    NUM_CREDITO = P_NUM_CREDITO;}

   --SELECCIONA EL MONTO TOTAL DEL CREDITO
  { SELECT MONTO_OTORGADO
   INTO   V_MONTO
   FROM   SD_MAESDOS
   WHERE  EMPRESA     = P_EMPRESA
   AND    NUM_CREDITO = P_NUM_CREDITO;}

  --ELIMINA EL REGISTRO DE SD_MOVDIA
   DELETE FROM SD_MOVDIA
   WHERE  EMPRESA     = P_EMPRESA
   AND    NUM_CREDITO = P_NUM_CREDITO
   AND    FECHA_MOV   = V_FECHA_HOY
   AND    FOLIO_SUC   = P_FOLIO_SUC
   ;

   RETURN P_COD_RET, P_MENSAJE;
   
END;
END PROCEDURE;