CREATE PROCEDURE "informix".sp_traspaso_hist_maesdos(P_EMPRESA        VARCHAR(3),
       P_NUM_CREDITO    VARCHAR(20),
       P_FECHA_HOY      DATE
      ) RETURNING VARCHAR(5), VARCHAR(80);


DEFINE P_COD_RET            VARCHAR(5);
DEFINE P_MENSAJE            VARCHAR(80);

DEFINE  SQL_ERR          INTEGER;
DEFINE  ISAM_ERR         INTEGER;
DEFINE  ERROR_INFO       VARCHAR(80);

BEGIN
  ON EXCEPTION SET SQL_ERR, ISAM_ERR, ERROR_INFO
     LET P_COD_RET  = SQL_ERR;
     LET P_MENSAJE  = ERROR_INFO;
     RETURN P_COD_RET, P_MENSAJE;
  END EXCEPTION;

  LET P_COD_RET  = '00000';
  LET P_MENSAJE  = 'PROCESO EXITOSO';


  INSERT INTO SD_HISTMAESDOS
         ( EMPRESA,	       FECHA_SALDO,       NUM_CREDITO,
	   FECHA_ULT_MOV,      SDO_INT_ANTICIP,   SDO_INT_ANT_DEV,  SDO_INTERESES,
	   SDO_DIA_ANT_INT,    SDO_MES_ANT_INT,   SDO_ACUM_MES_INT, FAVP,
	   SDO_ACUM_CAP_INT,   SDO_EXIG_INT,      SDO_NO_EXIG,      PROVISION_NORMAL,
	   DIAS_ACUM_INT,      SDO_MORATORIO,     SDO_DIA_ANT_MOR,  SDO_MES_ANT_MOR,
	   SDO_CONTAB_MORA,    DIAS_ACUM_MORA,    SDO_CAPITAL,      SDO_CAP_INSOLUTO,
	   SDO_DIA_ANT_CAP,    SDO_MES_ANT_CAP,   SDO_ACUM_MES_CAP, MTO_CAPITALIZADO,
	   MTO_MINITRA_CAP,    CARGOS_DIA_CAP,    ABONOS_DIA_CAP,   CARGOS_MES_CAP,
	   ABONOS_MES_CAP,     DIAS_ACUM_CAP,     MONTO_VENCIDO,    MTO_VENC_TRASP,
	   MONTO_FINANCIADO,   MONTO_RESERVADO,   SDO_ACUM_VENCIDO, DIAS_ACUM_INTPER,
	   SDO_GLOBAL_INT,     SDO_ACUM_INTPER,   MONTO_OTORGADO,   PROVI_VENC_NORMAL,
	   PROVI_VENC_ANTICIP, CAP_TRAS_NO_VENCI, MTO_VENC_INT,     MTO_VENC_TRA_INT,
	   MTO_FINAN_VDO,      MTO_RESER_INT,     MTO_FIN_VEN_TRASP,MTO_FIN_VIG_TRASP,
	   INT_TRA_NO_EXIG,    SDO_TRAB4)
  SELECT EMPRESA,            P_FECHA_HOY,       NUM_CREDITO,
	   FECHA_ULT_MOV,      SDO_INT_ANTICIP,   SDO_INT_ANT_DEV,  SDO_INTERESES,
	   SDO_DIA_ANT_INT,    SDO_MES_ANT_INT,   SDO_ACUM_MES_INT, FAVP,
	   SDO_ACUM_CAP_INT,   SDO_EXIG_INT,      SDO_NO_EXIG,      PROVISION_NORMAL,
	   DIAS_ACUM_INT,      SDO_MORATORIO,     SDO_DIA_ANT_MOR,  SDO_MES_ANT_MOR,
	   SDO_CONTAB_MORA,    DIAS_ACUM_MORA,    SDO_CAPITAL,      SDO_CAP_INSOLUTO,
	   SDO_DIA_ANT_CAP,    SDO_MES_ANT_CAP,   SDO_ACUM_MES_CAP, MTO_CAPITALIZADO,
	   MTO_MINISTRA_CAP,   CARGOS_DIA_CAP,    ABONOS_DIA_CAP,   CARGOS_MES_CAP,
	   ABONOS_MES_CAP,     DIAS_ACUM_CAP,     MONTO_VENCIDO,    MTO_VENC_TRASP,
	   MONTO_FINANCIADO,   MONTO_RESERVADO,   SDO_ACUM_VENCIDO, DIAS_ACUM_INTPER,
	   SDO_GLOBAL_INT,     SDO_ACUM_INTPER,   MONTO_OTORGADO,   PROVI_VENC_NORMAL,
	   PROVI_VENC_ANTICIP, CAP_TRAS_NO_VENCI, MTO_VENC_INT,     MTO_VENC_TRA_INT,
	   MTO_FINAN_VDO,      MTO_RESER_INT,     MTO_FIN_VEN_TRASP,MTO_FIN_VIG_TRASP,
	   INT_TRA_NO_EXIG,    SDO_TRAB4
  FROM  SD_MAESDOS
  WHERE EMPRESA     = P_EMPRESA
  AND   NUM_CREDITO = P_NUM_CREDITO;

  RETURN P_COD_RET, P_MENSAJE;
END;
END PROCEDURE;