CREATE PROCEDURE "informix".sp_plan_pagos(P_EMPRESA       VARCHAR(3)
                ,P_NUM_CREDITO   VARCHAR(20)
                ) RETURNING VARCHAR(5), VARCHAR(80);

DEFINE P_COD_RET           VARCHAR(5);
DEFINE P_MENSAJE           VARCHAR(80);

DEFINE V_FECHA_HOY         DATE;
DEFINE V_MONTO             DECIMAL(18,2);
DEFINE V_PERIODO_PAG_CAP   VARCHAR(1);
DEFINE V_PERIODO_PAG_INT   VARCHAR(1);
DEFINE V_TIPO_CALCULO      VARCHAR(2);
DEFINE V_SUCURSAL          VARCHAR(4);
DEFINE V_PERIODO_PLAZO     VARCHAR(1);
DEFINE V_PLAZO             INTEGER;
DEFINE V_TP_GEN_PLANPAGO   VARCHAR(1);
DEFINE V_GRACIA_CAP        INTEGER;
DEFINE V_DIFERIMIENTO_INT  INTEGER;
DEFINE V_EQUIVAL_CAP       INTEGER;
DEFINE V_EQUIVAL_INT       INTEGER;
DEFINE V_AJUSTE_DE_CUOTA   VARCHAR(1);
DEFINE V_AJUSTE_VENC_INT   VARCHAR(1);
DEFINE V_AJUSTE_VENCIM     VARCHAR(1);
DEFINE V_CUOTA_CON_DEC     VARCHAR(1);
define vnum_solicitud      char(20);

DEFINE V_FECHA_INI         DATE;
DEFINE V_FECHA_INICIO      DATE;
DEFINE V_FECHA_FINAL       DATE;
DEFINE V_FECHA_PRORRATEO   DATE;
DEFINE V_FECHA_PRIMIN      DATE;
DEFINE V_DIA_CUOTA         INTEGER;
DEFINE V_DIA_CORTE         VARCHAR(5);
DEFINE V_RANGO_DIAS        INTEGER;

DEFINE V_NUM_PRODUCTO      VARCHAR(4);
DEFINE V_VALOR             VARCHAR(200);
DEFINE V_CADENA            VARCHAR(200);

let V_CADENA = "";
BEGIN


  --SELECCIONA LA FECHA DE HOY
  SELECT FECHA_HOY INTO V_FECHA_HOY FROM SD_FECHAS WHERE EMPRESA = P_EMPRESA;

let P_NUM_CREDITO = P_NUM_CREDITO;
let vnum_solicitud = P_NUM_CREDITO[1,11];
let V_DIA_CORTE = "";

  --SELECCIONA LOS DATOS DEL CREDITO
  SELECT MSDO.MONTO_OTORGADO,  SOL.PERIODO_PAG_CAP, SOL.PERIODO_PAG_INT, SOL.TIPO_CALCULO,
         SOL.SUCURSAL,         SOL.PERIODO_PLAZO,   SOL.PLAZO,           SOL.TP_GEN_PLANPAGO,
         SOL.GRACIA_CAP,       SOL.DIFERIMIENTO_INT, SOL.FECHA_APERT_PROP,SOL.FECHA_VENC_PROP,
         SOL.AJUSTE_DE_CUOTA,  SOL.AJUSTE_VENC_INT,  SOL.AJUSTE_VENCIM,  SOL.CUOTA_CON_DEC,
         PCAP.EQUIVALENCIA_DIAS PCAP,
         PINT.EQUIVALENCIA_DIAS PINT,
         SOL.NUM_PRODUCTO
  INTO   V_MONTO,              V_PERIODO_PAG_CAP,   V_PERIODO_PAG_INT,   V_TIPO_CALCULO,
         V_SUCURSAL,           V_PERIODO_PLAZO,     V_PLAZO,             V_TP_GEN_PLANPAGO,
         V_GRACIA_CAP,         V_DIFERIMIENTO_INT,  V_FECHA_INICIO,      V_FECHA_FINAL,
         V_AJUSTE_DE_CUOTA,    V_AJUSTE_VENC_INT,   V_AJUSTE_VENCIM,     V_CUOTA_CON_DEC,
         V_EQUIVAL_CAP,        V_EQUIVAL_INT,
         V_NUM_PRODUCTO
  FROM   BDISOLIC:SS_SOLICITUDES SOL, SD_CODPCAP PCAP, SD_CODPINT PINT, SD_MAESDOS MSDO
  WHERE  MSDO.NUM_CREDITO = P_NUM_CREDITO
  AND    MSDO.EMPRESA = SOL.EMPRESA
  AND    PINT.PERIOD_PAG_INT = SOL.PERIODO_PAG_INT
  AND    PINT.EMPRESA = SOL.EMPRESA
  AND    PCAP.PERIOD_PAGO_CAP = SOL.PERIODO_PAG_CAP
  AND    PCAP.EMPRESA = SOL.EMPRESA
  AND    SOL.EMPRESA = P_EMPRESA
  AND    SOL.NUM_SOLICITUD = vnum_solicitud;

LET V_TIPO_CALCULO = V_TIPO_CALCULO;

  --SE GENERA EL PLAN DE PAGOS CON LA FECHA DE APERTURA
  IF V_TP_GEN_PLANPAGO = '1' THEN
     IF V_FECHA_INICIO <  V_FECHA_HOY THEN
       LET V_FECHA_INICIO = V_FECHA_HOY;
     END IF;
  --SE GENERA EL PLAN DE PAGOS CON LA FECHA DE LA PRIMERA MINISTRACION
  ELSE

     SELECT MIN(FECHA_PROGRAMADA)
     INTO V_FECHA_INICIO
     FROM SD_DETMINIS
     WHERE NUM_CREDITO = P_NUM_CREDITO
     AND   EMPRESA = P_EMPRESA;

     IF V_FECHA_INICIO < V_FECHA_HOY  THEN
        LET V_FECHA_INICIO = V_FECHA_HOY;
     END IF;
  END IF;

  EXECUTE PROCEDURE SP_CALCULA_FECHA(P_EMPRESA,V_GRACIA_CAP,V_PERIODO_PLAZO,V_FECHA_INICIO
                                    ,'N', V_AJUSTE_VENC_INT)
               INTO P_COD_RET, P_MENSAJE, V_FECHA_PRORRATEO;

  IF V_FECHA_PRORRATEO > V_FECHA_INICIO THEN
     LET V_FECHA_INICIO = V_FECHA_PRORRATEO;
  ELSE
     LET V_FECHA_PRORRATEO = NULL;
  END IF;

  SELECT DIA_CUOTA
  INTO   V_DIA_CUOTA
  FROM   SD_DEFINICION
  WHERE  NUM_PRODUCTO = V_NUM_PRODUCTO
  AND    EMPRESA = P_EMPRESA;

  SELECT V_EQUIVAL_CAP*(VALOR/100)
  INTO   V_RANGO_DIAS
  FROM SD_PARAM
  WHERE COD_PARAM = '52'
  AND EMPRESA = P_EMPRESA;

  IF V_DIA_CUOTA > 0 AND V_DIA_CUOTA <= 28 THEN
    LET V_FECHA_INI = MDY(MONTH(V_FECHA_INICIO),V_DIA_CUOTA,YEAR(V_FECHA_INICIO));
    IF DAY(V_FECHA_INICIO) >= V_DIA_CUOTA THEN
      IF (V_FECHA_INI - V_FECHA_HOY) < V_RANGO_DIAS THEN
        LET V_FECHA_INI = V_FECHA_INI + 1 UNITS MONTH;
      END IF

      EXECUTE PROCEDURE SP_CALCULA_FECHA(P_EMPRESA,1,V_PERIODO_PLAZO,V_FECHA_INI
                                        ,'N', V_AJUSTE_VENC_INT)
                   INTO P_COD_RET, P_MENSAJE, V_FECHA_INICIO;
    ELSE
      IF (V_FECHA_INI - V_FECHA_INICIO) < V_RANGO_DIAS THEN
	LET V_FECHA_INI = V_FECHA_INI + 1 UNITS MONTH;
        EXECUTE PROCEDURE SP_CALCULA_FECHA(P_EMPRESA,1,V_PERIODO_PLAZO,
					   V_FECHA_INI, 'N', V_AJUSTE_VENC_INT)
                     INTO P_COD_RET, P_MENSAJE, V_FECHA_INICIO;
      ELSE
        LET V_FECHA_INICIO = V_FECHA_INI;
      END IF;
    END IF;
    LET V_DIA_CORTE = "50";
  ELIF V_DIA_CUOTA = 50 THEN
    IF (V_FECHA_INICIO - V_FECHA_HOY)  < V_RANGO_DIAS THEN
	--LET V_FECHA_INICIO = V_FECHA_INICIO + 1 UNITS MONTH;
       EXECUTE PROCEDURE SP_CALCULA_FECHA(P_EMPRESA,1,V_PERIODO_PLAZO,V_FECHA_INICIO
                                         ,'N', V_AJUSTE_VENC_INT)
                    INTO P_COD_RET, P_MENSAJE, V_FECHA_INICIO;
    END IF;
   LET V_DIA_CORTE = "50";
  ELIF V_DIA_CUOTA = 99 THEN
    IF MONTH(V_FECHA_INICIO) = 12 THEN
       LET V_FECHA_INI = MDY(12,31,YEAR(V_FECHA_INICIO));
    ELSE
       LET V_FECHA_INI = MDY(MONTH(V_FECHA_INICIO)+1,1,YEAR(V_FECHA_INICIO))-1;
    END IF;
    IF (V_FECHA_INI - V_FECHA_INICIO) < V_RANGO_DIAS THEN
       LET V_FECHA_INICIO = V_FECHA_INI;
       EXECUTE PROCEDURE SP_CALCULA_FECHA(P_EMPRESA,1,V_PERIODO_PLAZO,V_FECHA_INICIO
                                         ,'N', V_AJUSTE_VENC_INT)
                    INTO P_COD_RET, P_MENSAJE, V_FECHA_INICIO;
    ELSE
       LET V_FECHA_INICIO = V_FECHA_INI;
    END IF;
    LET V_DIA_CORTE = "99";
  ELIF V_DIA_CUOTA = 15 AND V_PERIODO_PLAZO = 'Q' THEN
    EXECUTE PROCEDURE SP_CALCULA_FECHA(P_EMPRESA,1,V_PERIODO_PLAZO,V_FECHA_INI
                                      ,'N', V_AJUSTE_VENC_INT)
                 INTO P_COD_RET, P_MENSAJE, V_FECHA_INICIO;
    LET V_DIA_CORTE ="50";
  END IF;


  --IF V_PERIODO_PAG_INT <> "1" THEN
       EXECUTE PROCEDURE SP_CALCULA_FECHA(P_EMPRESA,V_PLAZO-1,V_PERIODO_PLAZO,
					  V_FECHA_INICIO,'N',V_AJUSTE_VENC_INT)
                  INTO P_COD_RET, P_MENSAJE, V_FECHA_FINAL;
  --ELSE
  --     EXECUTE PROCEDURE SP_CALCULA_FECHA(P_EMPRESA,V_PLAZO,V_PERIODO_PLAZO,
--					  V_FECHA_INICIO,'N',V_AJUSTE_VENC_INT)
 --                 INTO P_COD_RET, P_MENSAJE, V_FECHA_FINAL;

  --END IF

  UPDATE sd_maecred SET fecha_vencim = V_FECHA_FINAL
   WHERE num_credito = P_NUM_CREDITO
     AND empresa = P_EMPRESA;

  EXECUTE PROCEDURE CAPITAL(P_EMPRESA
                              ,P_NUM_CREDITO
                              ,V_FECHA_INICIO
                              ,V_FECHA_FINAL
                              ,V_MONTO
                              ,V_PERIODO_PAG_CAP
                              ,V_CUOTA_CON_DEC
                              ,V_AJUSTE_VENCIM
                              ,V_AJUSTE_DE_CUOTA
                              ,V_AJUSTE_VENC_INT
                              ,V_DIA_CORTE
                              ,V_FECHA_PRORRATEO
                              )
                         INTO  P_COD_RET, P_MENSAJE;

     EXECUTE PROCEDURE INTERES(P_EMPRESA
                              ,P_NUM_CREDITO
                              ,V_FECHA_INICIO
                              ,V_FECHA_FINAL
                              ,V_MONTO
                              ,V_PERIODO_PAG_INT
                              ,V_CUOTA_CON_DEC
                              ,V_AJUSTE_VENC_INT
                              ,V_AJUSTE_DE_CUOTA
                              ,V_TIPO_CALCULO
                              ,V_DIA_CORTE
                              ,V_FECHA_PRORRATEO
                              )
                         INTO  P_COD_RET, P_MENSAJE;


  --VERIFICA QUE EL PRODUCTO NO SEA DE CONSTRUCCION
  SELECT ','||TRIM(VALOR)||','
  INTO   V_VALOR
  FROM   SD_PARAM
  WHERE  COD_PARAM = '53'
  AND    EMPRESA = P_EMPRESA;

  IF V_CADENA = V_VALOR THEN  --NO ES DE CONSTRUCCION
     EXECUTE PROCEDURE PAGOS_NIVELADOS (P_EMPRESA, P_NUM_CREDITO, V_FECHA_INICIO)
                                  INTO  P_COD_RET, P_MENSAJE;
  ELSE  --ES DE CONSTRUCCION
     DELETE FROM SD_PAGOCAPIT WHERE EMPRESA = P_EMPRESA AND NUM_CREDITO = P_NUM_CREDITO;
     UPDATE SD_MAECRED SET TIPO_CALCULO = '02' WHERE EMPRESA = P_EMPRESA AND NUM_CREDITO = P_NUM_CREDITO;
  END IF;

  RETURN P_COD_RET, P_MENSAJE;
END;
END PROCEDURE;