CREATE PROCEDURE "informix".sp_provision_morat(P_EMPRESA         VARCHAR(3),
       P_NUM_CREDITO     VARCHAR(20),
       P_FECHA_CUOTA     DATE,
       P_EJECUTIVO       VARCHAR(8),
       P_PRODUCTO        LIKE SD_MAECRED.NUM_PRODUCTO,
       P_SUCURSAL        LIKE SD_MAECRED.SUCURSAL,
       P_DIVISA	       LIKE SD_MAECRED.DIVISA,
       P_FECHA_MOV	 DATE,
       P_FUNCION         LIKE SD_TRANSFUN.CODIGO_FUN,
       P_MORATORIO       DECIMAL(18,2),
       P_MORA_COPE       DECIMAL(18,2),
       P_DIAS_CALC       INTEGER
      )RETURNING VARCHAR(6), VARCHAR(80);

DEFINE P_COD_RET     VARCHAR(6);
DEFINE P_MENSAJE     VARCHAR(80);

DEFINE V_REFERENCIA  INTEGER;
DEFINE V_TRANSACC    VARCHAR(4);
DEFINE V_FOLIO	   VARCHAR(16);
DEFINE V_CONTADOR    INTEGER;
DEFINE V_ACTUALIZA   INTEGER;
DEFINE V_NUM_REG     INTEGER;
DEFINE V_HORA        VARCHAR(8);

DEFINE  SQL_ERR      INTEGER;
DEFINE  ISAM_ERR     INTEGER;
DEFINE  ERROR_INFO   VARCHAR(80);

BEGIN
  ON EXCEPTION SET SQL_ERR, ISAM_ERR, ERROR_INFO
     LET P_COD_RET  = SQL_ERR;
     LET P_MENSAJE  = ERROR_INFO;
     RETURN P_COD_RET, P_MENSAJE;
  END EXCEPTION;

  LET V_TRANSACC = '0000';
  LET P_COD_RET  = '00000';
  LET P_MENSAJE  = 'PROCESO EXITOSO';
  LET V_REFERENCIA = NULL;
  LET V_HORA = REPLACE(REPLACE(
               REPLACE(EXTEND(CURRENT HOUR TO FRACTION)
               , ':',''),'.',''),'-','');
  LET V_FOLIO = P_EJECUTIVO || V_HORA;

  SELECT COUNT(*) INTO V_NUM_REG FROM SD_DETMORA 
  WHERE FECHA_CUOTA = P_FECHA_CUOTA
  AND NUM_CREDITO = P_NUM_CREDITO
  AND EMPRESA = P_EMPRESA;

  --SE HACE LA AFECTACION A SD_DETMORA
  IF V_NUM_REG > 0 THEN
    UPDATE SD_DETMORA
    SET SDO_MORA_ORDI = NVL(SDO_MORA_ORDI,0) + NVL(P_MORATORIO,0)
       ,SDO_MORA_COPE = NVL(SDO_MORA_COPE,0) + NVL(P_MORA_COPE,0)
    WHERE FECHA_CUOTA = P_FECHA_CUOTA
    AND NUM_CREDITO = P_NUM_CREDITO 
    AND EMPRESA = P_EMPRESA;
  ELSE
    INSERT INTO SD_DETMORA VALUES
        (P_EMPRESA, P_NUM_CREDITO, P_FECHA_CUOTA, 'N', 0,0,0,0,0
        ,NVL(P_MORATORIO,0),NVL(P_MORA_COPE,0));
  END IF;

  UPDATE SD_MAESDOS 
  SET    SDO_DIA_ANT_MOR = SDO_MORATORIO,
         SDO_MORATORIO   = NVL(SDO_MORATORIO,0) + NVL(P_MORATORIO,0) + NVL(P_MORA_COPE,0)
  WHERE  NUM_CREDITO = P_NUM_CREDITO
  AND    EMPRESA     = P_EMPRESA;

  UPDATE SD_PAGOCAPIT
  SET    STATUS_MORATORIO = '2',
         DIAS_MORATORIOS = NVL(DIAS_MORATORIOS,0) + P_DIAS_CALC,
         MONTO_MORATORIO = NVL(MONTO_MORATORIO, 0) + P_MORATORIO + P_MORA_COPE
  WHERE  NUM_CREDITO  = P_NUM_CREDITO
  AND    EMPRESA      = P_EMPRESA
  AND    FECHA_CUOTA  = P_FECHA_CUOTA;

  SELECT MAX(CODIGO_REF)
  INTO   V_REFERENCIA
  FROM   SD_TRANSFUN
  WHERE  EMPRESA    = P_EMPRESA
  AND    CODIGO_FUN = P_FUNCION
  AND    CODIGO_INS = (SELECT VALOR
                       FROM   SD_PARAM
                       WHERE  EMPRESA    = P_EMPRESA
                       AND    COD_PARAM  = '40');

  IF V_REFERENCIA IS NOT NULL THEN
     /* Provision de Moratorios por Tasa Ordinaria */
     execute procedure GENMOV(P_EMPRESA, P_NUM_CREDITO, P_PRODUCTO, V_REFERENCIA
                             ,P_FUNCION, P_FECHA_MOV, P_MORATORIO, V_FOLIO
                             ,P_SUCURSAL, P_DIVISA, V_TRANSACC
                             )INTO P_COD_RET, P_MENSAJE;
  ELSE
     LET P_COD_RET = '961';
     LET P_MENSAJE = 'REFERENCIA EN SD_PARAM NO VALIDA "40"';
  END IF;

  RETURN P_COD_RET, P_MENSAJE;
END;
END PROCEDURE;