CREATE PROCEDURE "informix".revgar( P_EMPRESA       LIKE BDICRED:SD_MAECRED.EMPRESA
                        , P_CREDITO_NVO   LIKE BDICRED:SD_MAECRED.NUM_CREDITO
                        , P_CREDITO_OLD   LIKE BDICRED:SD_MAECRED.NUM_CREDITO
                        )
RETURNING VARCHAR(10), VARCHAR(80);
--P_ERROR         OUT  VARCHAR2
--P_MENSAJE       OUT  VARCHAR2

DEFINE SQL_ERR    INTEGER;
DEFINE ISAM_ERR   INTEGER;
DEFINE ERROR_INFO VARCHAR(200);

DEFINE P_ERROR    VARCHAR(10);
DEFINE P_MENSAJE  VARCHAR(80);

BEGIN
   ON EXCEPTION SET SQL_ERR, ISAM_ERR, ERROR_INFO
      LET P_ERROR   = SQL_ERR;
      LET P_MENSAJE = ERROR_INFO;
      RETURN P_ERROR, P_MENSAJE;
   END EXCEPTION;

   LET P_ERROR   = '00000';
   LET P_MENSAJE = 'PROCESO EXITOSO';


    DELETE FROM sg_maegaran
     WHERE num_credito = P_CREDITO_NVO;

    DELETE FROM sg_aval
     WHERE num_credito = P_CREDITO_NVO; 


{   INSERT INTO SG_MAEGARAN(EMPRESA        ,NUM_CREDITO
                          ,ID_GARAN       ,COD_GARAN
                          ,GRUPO_GARAN    ,DIVISA
                          ,VAL_GARANTOT   ,STATUSGAR
                          ,USER_INSERT    ,FECHA_INSERT
                          )
                   SELECT  EMPRESA        ,P_CREDITO_OLD
                          ,ID_GARAN       ,COD_GARAN
                          ,GRUPO_GARAN    ,DIVISA
                          ,VAL_GARANTOT   ,STATUSGAR
                          ,USER_INSERT    ,FECHA_INSERT
                    FROM   SG_MAEGARAN
                    WHERE  NUM_CREDITO = P_CREDITO_NVO
                    AND    EMPRESA     = P_EMPRESA;

   UPDATE SG_FINAN
      SET NUM_CREDITO = P_CREDITO_OLD
    WHERE NUM_CREDITO = P_CREDITO_NVO
      AND EMPRESA     = P_EMPRESA;

   UPDATE SG_PREND
      SET NUM_CREDITO = P_CREDITO_OLD
    WHERE NUM_CREDITO = P_CREDITO_NVO
      AND EMPRESA     = P_EMPRESA;

   UPDATE SG_COMER
      SET NUM_CREDITO = P_CREDITO_OLD
    WHERE NUM_CREDITO = P_CREDITO_NVO
      AND EMPRESA     = P_EMPRESA;

   UPDATE SG_AVAL
      SET NUM_CREDITO = P_CREDITO_OLD
    WHERE NUM_CREDITO = P_CREDITO_NVO
      AND EMPRESA     = P_EMPRESA;

   UPDATE SG_FIDUC
      SET NUM_CREDITO = P_CREDITO_OLD
    WHERE NUM_CREDITO = P_CREDITO_NVO
     AND  EMPRESA     = P_EMPRESA;

   UPDATE SG_HIPOT
      SET NUM_CREDITO = P_CREDITO_OLD
    WHERE NUM_CREDITO = P_CREDITO_NVO
      AND EMPRESA     = P_EMPRESA;

   UPDATE SG_SEGUR
      SET NUM_CREDITO = P_CREDITO_OLD
    WHERE NUM_CREDITO = P_CREDITO_NVO
      AND EMPRESA     = P_EMPRESA;

   DELETE FROM SG_MAEGARAN
    WHERE NUM_CREDITO = P_CREDITO_NVO
      AND EMPRESA     = P_EMPRESA;}

   RETURN P_ERROR, P_MENSAJE;

END;
END PROCEDURE;